import program from "@peated/cli/program";
import { db } from "@peated/server/db";
import { tags } from "@peated/server/db/schema";
import type { FlavorProfile, TagCategory } from "@peated/server/types";

const TAGS: Record<TagCategory, string[]> = {
  cereal: [
    "barley_sugar",
    "biscuity",
    "oatmeal",
    "grains",
    "malted_barley",
    "rye",
    "wheat",
    "corn",
    "fresh_hay",
    "bread",
  ],
  fruity: [
    "acidic",
    "anise",
    "baking_spices",
    "green_apple",
    "lemon_zest",
    "fresh_berries",
    "citrus",
    "lime",
    "ripe_peach",
    "juicy_pear",
    "mellow_apricot",
    "soft_cherry",
    "ripe_melon",
    "banana",
    "apple_pie",
    "stewed_fruits",
  ],
  floral: [
    "light_floral",
    "soft_floral",
    "lavender",
    "fresh_flowers",
    "green_leaves",
    "heather",
    "delicate_herbs",
  ],
  peaty: [
    "alcohol_burn",
    "light_smoke",
    "gentle_peat",
    "smoked_herbs",
    "peat_moss",
    "earthy_peat",
    "smoked_wood",
    "balanced_smoke",
    "intense_smoke",
    "heavy_iodine",
    "tar",
    "burnt_rubber",
    "creosote",
    "smoked_meat",
    "charred_oak",
    "deep_peat",
  ],
  feinty: [
    "old_books",
    "antique_leather",
    "tobacco",
    "earthiness",
    "soft_musk",
    "aged_sherry",
    "library_books",
    "tobacco_leaf",
  ],
  sulphury: ["burnt_matches", "gunpowder"],
  woody: [
    "old_oak",
    "polished_wood",
    "vanilla_bean",
    "creamy_oak",
    "maple_syrup",
    "butterscotch",
    "ripe_apples",
    "toasted_almonds",
    "oak_spices",
    "juicy_pears",
    "antique_wood",
    "oak",
    "sherry",
  ],
  winey: [
    "luxurious_sherry",
    "dark_chocolate",
    "walnut",
    "coffee_beans",
    "date",
    "currants",
    "rich_prunes",
    "dried_figs",
    "raisins",
    "fruit_cake",
  ],
};

const PROFILES: Record<FlavorProfile, string[]> = {
  young_spritely: [
    "green_apple",
    "lemon_zest",
    "fresh_berries",
    "citrus",
    "grass",
    "lime",
    "light_floral",
    "sparkling",
  ],
  sweet_fruit_mellow: [
    "cake",
    "candy",
    "ripe_peach",
    "juicy_pear",
    "mellow_apricot",
    "soft_cherry",
    "barley_sugar",
    "marmalade",
    "ripe_melon",
    "banana",
  ],
  spicy_sweet: [
    "anise",
    "baking_spices",
    "cinnamon",
    "sweet_ginger",
    "vanilla",
    "caramel",
    "honey",
    "rich_nutmeg",
    "warm_clove",
    "spiced_cake",
  ],
  spicy_dry: [
    "bitter",
    "fiery",
    "dry_pepper",
    "herbal_notes",
    "crisp_ginger",
    "subtle_oak",
    "cardamom",
    "sandalwood",
    "black_tea",
    "tobacco_leaf",
  ],
  deep_rich_dried_fruit: [
    "dried_figs",
    "raisins",
    "rich_prunes",
    "luxurious_sherry",
    "dark_chocolate",
    "walnut",
    "coffee_beans",
    "date",
  ],
  old_dignified: [
    "balanced",
    "antique_leather",
    "old_oak",
    "tobacco",
    "polished_wood",
    "earthiness",
    "soft_musk",
    "aged_sherry",
    "library_books",
  ],
  light_delicate: [
    "acidic",
    "clean",
    "soft_floral",
    "lavender",
    "green_leaves",
    "light_honey",
    "almond",
    "heather",
    "fresh_hay",
    "delicate_herbs",
  ],
  juicy_oak_vanilla: [
    "butter",
    "vanilla_bean",
    "creamy_oak",
    "maple_syrup",
    "butterscotch",
    "ripe_apples",
    "toasted_almonds",
    "oak_spices",
    "juicy_pears",
  ],
  oily_coastal: [
    "ethanol",
    "seaweed",
    "oily_texture",
    "salt_spray",
    "maritime_air",
    "briny_notes",
    "clam",
    "oyster",
    "fishing_net",
  ],
  lightly_peated: [
    "ethanol",
    "light_smoke",
    "gentle_peat",
    "fresh_mineral",
    "smoked_herbs",
    "bonfire_embers",
    "peat_moss",
    "autumn_leaves",
    "grilled_citrus",
  ],
  peated: [
    "earthy_peat",
    "smoked_wood",
    "balanced_smoke",
    "leather",
    "campfire",
    "black_pepper",
    "wet_stones",
    "forest_floor",
  ],
  heavily_peated: [
    "alcohol_burn",
    "fiery",
    "intense_smoke",
    "heavy_iodine",
    "tar",
    "burnt_rubber",
    "creosote",
    "smoked_meat",
    "charred_oak",
    "deep_peat",
  ],
};

const subcommand = program.command("data");

subcommand.command("load-default-tags").action(async (options) => {
  Object.entries(TAGS).forEach(async ([categoryName, tagList]) => {
    db.transaction(async (tx) => {
      for (const tagName of tagList) {
        console.log(`Registering tag ${tagName}`);
        tx.insert(tags)
          .values({
            name: tagName,
            tagCategory: categoryName as TagCategory,
            flavorProfiles: Object.entries(PROFILES)
              .filter(([profileName, tagList]) => tagList.includes(tagName))
              .map<FlavorProfile>(
                ([profileName]) => profileName as FlavorProfile,
              ),
          })
          .onConflictDoNothing();
      }
    });
  });
});
