export const defaultHeaders = (url: string) => {
  const urlParts = new URL(url);
  return {
    Authority: urlParts.hostname,
    "User-Agent":
      "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/114.0.0.0 Safari/537.36",
    Accept:
      "text/html,application/xhtml+xml,application/xml;q=0.9,image/avif,image/webp,image/apng,*/*;q=0.8,application/signed-exchange;v=b3;q=0.7,",
    "Accept-Language": "en-US,en:q=0.9",
    Referer: urlParts.origin,
  };
};

// https://www.whiskysaga.com/smws-codes
export const SMWS_DISTILLERY_CODES: Record<string, string> = {
  // Single Malt
  1: "Glenfarclas",
  2: "Glenlivet",
  3: "Bowmore",
  4: "Highland Park",
  5: "Auchentoshan",
  6: "Macduff",
  7: "Longmorn",
  8: "Tamdhu",
  9: "Glen Grant",
  10: "Bunnahabhain",
  11: "Tomatin",
  12: "BenRiach",
  13: "Dalmore",
  14: "Talisker",
  15: "Glenfiddich",
  16: "Glenturret",
  17: "Scapa",
  18: "Inchgower",
  19: "Glen Garioch",
  20: "Inverleven",
  21: "Glenglassaugh",
  22: "Glenkinchie",
  23: "Bruichladdich",
  24: "Macallan",
  25: "Rosebank",
  26: "Clynelish",
  27: "Springbank",
  28: "Tullibardine",
  29: "Laphroaig",
  30: "Glenrothes",
  31: "Isle of Jura",
  32: "Edradour",
  33: "Ardbeg",
  34: "Tamnavulin",
  35: "Glen Moray",
  36: "Benrinnes",
  37: "Cragganmore",
  38: "Caperdonich",
  39: "Linkwood",
  40: "Balvenie",
  41: "Dailuaine",
  42: "Tobermory",
  43: "Port Ellen",
  44: "Craigellachie",
  45: "Dallas Dhu",
  46: "Glenlossie",
  47: "Benromach",
  48: "Balmenach",
  49: "St. Magdalene",
  50: "Bladnoch",
  51: "Bushmills",
  52: "Old Pulteney",
  53: "Caol Ila",
  54: "Aberlour",
  55: "Royal Brackla",
  56: "Coleburn",
  57: "Glen Mhor",
  58: "Strathisla",
  59: "Teaninich",
  60: "Aberfeldy",
  61: "Brora",
  62: "Glenlochy",
  63: "Glentauchers",
  64: "Mannochmore",
  65: "Imperial",
  66: "Ardmore",
  67: "Banff",
  68: "Blair Athol",
  69: "Glen Albyn",
  70: "Balblair",
  71: "Glenburgie",
  72: "Miltonduff",
  73: "Aultmore",
  74: "North Port",
  75: "Glenury / Glenury Royal",
  76: "Mortlach",
  77: "Glen Ord",
  78: "Ben Nevis",
  79: "Deanston",
  80: "Glen Spey",
  81: "Glen Keith",
  82: "Glencadam",
  83: "Convalmore",
  84: "Glendullan",
  85: "Glen Elgin",
  86: "Glenesk",
  87: "Millburn",
  88: "Speyburn",
  89: "Tomintoul",
  90: "Pittyvaich",
  91: "Dufftown",
  92: "Lochside",
  93: "Glen Scotia",
  94: "Fettercairn",
  95: "Auchroisk",
  96: "GlenDronach",
  97: "Littlemill",
  98: "Inverleven",
  99: "Glenugie",
  100: "Strathmill",
  101: "Knockando",
  102: "Dalwhinnie",
  103: "Royal Lochnagar",
  104: "Glenburgie (Glencraig)",
  105: "Tormore",
  106: "Cardhu",
  107: "Glenallachie",
  108: "Allt-a-Bhainne",
  109: "Miltonduff (Mosstowie)",
  110: "Oban",
  111: "Lagavulin",
  112: "Loch Lomond (Inchmurrin)",
  113: "Braeval (Braes of Glenlivet)",
  114: "Springbank (Longrow)",
  115: "Knockdhu (AnCnoc)",
  116: "Yoichi",
  117: "Cooley (Unpeated)",
  118: "Cooley / Connemara (Peated)",
  119: "Yamazaki",
  120: "Hakushu",
  121: "Isle of Arran",
  122: "Loch Lomond (Croftengea)",
  123: "Glengoyne",
  124: "Miyagikyo",
  125: "Glenmorangie",
  126: "Springbank (Hazelburn)",
  127: "Bruichladdich (Port Charlotte)",
  128: "Penderyn",
  129: "Kilchoman",
  130: "Chichibu",
  131: "Hanyu",
  132: "Karuizawa",
  133: "Westland",
  134: "Paul John",
  135: "Loch Lomond (Inchmoan)",
  136: "Eden Mill",
  137: "St. George’s (The English Whisky Co.)",
  138: "Nantou",
  139: "Kavalan",
  140: "Balcones",
  141: "Fary Lochan",
  142: "Breuckelen Distilling",
  143: "Copperworks Distilling Co.",
  144: "High Coast Distillery (formerly Box Whisky)",
  145: "Smögen Whisky",
  146: "Cotswolds",
  147: "Archie Rose",
  148: "Starward",
  149: "Ardnamurchan",
  150: "West Cork Distillers",
  151: "Mackmyra",
  152: "Shelter Point",
  153: "Thy Whisky",
  154: "Mosgaard Whisky",
  155: "Milk & Honey Distillery",
  156: "Glasgow Distillery",
  157: "Distillerie de Warenghem (Armorik)",
  158: "Yuza Distillery",

  // Single Grain
  G1: "North British",
  G2: "Carsebridge",
  G3: "Caledonian",
  G4: "Cameronbridge",
  G5: "Invergordon",
  G6: "Port Dundas",
  G7: "Girvan",
  G8: "Cambus",
  G9: "Loch Lomond",
  G10: "Strathclyde",
  G11: "Nikka Coffey Grain",
  G12: "Nikka Coffey Malt",
  G13: "Chita",
  G14: "Dumbarton",
  G15: "Loch Lomond (Rhosdhu)",
  G16: "Glasgow Distillery",

  // Bourbon
  B1: "Heaven Hill",
  B2: "New Bernheim",
  B3: "Rock Town",
  B4: "FEW Spirits",
  B5: "George Dickel (Cascade Hollow)",
  B6: "Finger Lakes Distilling",
  B7: "MGP (Midwest Grain Products)",

  // Rye
  RW1: "FEW Spirits",
  RW2: "Finger Lakes Distilling",
  RW3: "New York Distilling Co.",
  RW4: "Peerless Distillery",
  RW5: "MGP",
  RW6: "Kyrö Distillery",

  // Corn
  CW1: "Heaven Hill",

  // Rum
  R1: "Monymusk",
  R2: "Demerara Distillers (El Dorado)",
  R3: "West Indies Rum",
  R4: "Trinidad Distillers (Angostura)",
  R5: "Long Pond",
  R6: "Foursquare",
  R7: "Hampden",
  R8: "Compañía Licorera de Nicaragua (Flor de Caña)",
  R9: "Varela Hermanos (Ron Abuelo)",
  R10: "Trinidad Distiller’s",
  R11: "Worthy Park",
  R12: "Travellers",
  R13: "Caroni",
  R14: "Uitvlugt",

  // Armagnac
  A1: "Chateau de Lacaze",
  A2: "Domaine Laguille",
  A3: "J. Goudoulin (Veuve Goudoulin)",
  A4: "Domaine d’Espérance",
  A5: "Chateau de Laubade",
  A6: "Domaine Lasalle",
  A7: "Domaine Lasalle",
  A8: "Domaine de Cavaillon",

  // Cognac
  C1: "Camus",
  C2: "Domaine de Chez Guérive",
  C3: "Louis Royer",
  C4: "Distillery D’Aumagne",
  C5: "Tiffon Cognac",
  C6: "M & H Bonneau",
  C7: "Guy Rateau",
  C8: "Marie C. Bodit",
  C9: "Robert Audebeau",

  // Gin
  GN1: "Glasgow Distillery Company",
  GN2: "Strathearn Distillers",
  GN3: "The Borders Distillery",
  GN4: "Boatyard Distillery",
  GN5: "Scottish Gin",
  GN6: "Holyrood Distillery",
};
