export const DEFAULT_CREATED_BY_ID = 1;

export const MAX_FILESIZE = 1048576 * 20;

export const XP_PER_LEVEL = 5;

export const COUNTRY_LIST = [
  "Afghanistan",
  "Albania",
  "Algeria",
  "American Samoa",
  "Andorra",
  "Angola",
  "Anguilla",
  "Antarctica",
  "Antigua and Barbuda",
  "Argentina",
  "Armenia",
  "Aruba",
  "Australia",
  "Austria",
  "Azerbaijan",
  "Bahamas",
  "Bahrain",
  "Bangladesh",
  "Barbados",
  "Belarus",
  "Belgium",
  "Belize",
  "Benin",
  "Bermuda",
  "Bhutan",
  "Bolivia (Plurinational State of)",
  "Bonaire, Sint Eustatius and Saba",
  "Bosnia and Herzegovina",
  "Botswana",
  "Bouvet Island",
  "Brazil",
  "British Indian Ocean Territory",
  "Brunei Darussalam",
  "Bulgaria",
  "Burkina Faso",
  "Burundi",
  "Cabo Verde",
  "Cambodia",
  "Cameroon",
  "Canada",
  "Cayman Islands",
  "Central African Republic",
  "Chad",
  "Chile",
  "China",
  "Christmas Island",
  "Cocos (Keeling) Islands",
  "Colombia",
  "Comoros",
  "Congo (the Democratic Republic of the)",
  "Congo",
  "Cook Islands",
  "Costa Rica",
  "Croatia",
  "Cuba",
  "Curaçao",
  "Cyprus",
  "Czechia",
  "Côte d'Ivoire",
  "Denmark",
  "Djibouti",
  "Dominica",
  "Dominican Republic",
  "Ecuador",
  "Egypt",
  "El Salvador",
  "Equatorial Guinea",
  "Eritrea",
  "Estonia",
  "Eswatini",
  "Ethiopia",
  "Falkland Islands (the) [Malvinas]",
  "Faroe Islands",
  "Fiji",
  "Finland",
  "France",
  "French Guiana",
  "French Polynesia",
  "French Southern Territories",
  "Gabon",
  "Gambia",
  "Georgia",
  "Germany",
  "Ghana",
  "Gibraltar",
  "Greece",
  "Greenland",
  "Grenada",
  "Guadeloupe",
  "Guam",
  "Guatemala",
  "Guernsey",
  "Guinea",
  "Guinea-Bissau",
  "Guyana",
  "Haiti",
  "Heard Island and McDonald Islands",
  "Holy See",
  "Honduras",
  "Hong Kong",
  "Hungary",
  "Iceland",
  "India",
  "Indonesia",
  "Iran (Islamic Republic of)",
  "Iraq",
  "Ireland",
  "Isle of Man",
  "Israel",
  "Italy",
  "Jamaica",
  "Japan",
  "Jersey",
  "Jordan",
  "Kazakhstan",
  "Kenya",
  "Kiribati",
  "Korea (the Democratic People's Republic of)",
  "Korea (the Republic of)",
  "Kuwait",
  "Kyrgyzstan",
  "Lao People's Democratic Republic",
  "Latvia",
  "Lebanon",
  "Lesotho",
  "Liberia",
  "Libya",
  "Liechtenstein",
  "Lithuania",
  "Luxembourg",
  "Macao",
  "Madagascar",
  "Malawi",
  "Malaysia",
  "Maldives",
  "Mali",
  "Malta",
  "Marshall Islands",
  "Martinique",
  "Mauritania",
  "Mauritius",
  "Mayotte",
  "Mexico",
  "Micronesia (Federated States of)",
  "Moldova (the Republic of)",
  "Monaco",
  "Mongolia",
  "Montenegro",
  "Montserrat",
  "Morocco",
  "Mozambique",
  "Myanmar",
  "Namibia",
  "Nauru",
  "Nepal",
  "Netherlands",
  "New Caledonia",
  "New Zealand",
  "Nicaragua",
  "Niger",
  "Nigeria",
  "Niue",
  "Norfolk Island",
  "Northern Mariana Islands",
  "Norway",
  "Oman",
  "Pakistan",
  "Palau",
  "Palestine, State of",
  "Panama",
  "Papua New Guinea",
  "Paraguay",
  "Peru",
  "Philippines",
  "Pitcairn",
  "Poland",
  "Portugal",
  "Puerto Rico",
  "Qatar",
  "Republic of North Macedonia",
  "Romania",
  "Russian Federation",
  "Rwanda",
  "Réunion",
  "Saint Barthélemy",
  "Saint Helena, Ascension and Tristan da Cunha",
  "Saint Kitts and Nevis",
  "Saint Lucia",
  "Saint Martin (French part)",
  "Saint Pierre and Miquelon",
  "Saint Vincent and the Grenadines",
  "Samoa",
  "San Marino",
  "Sao Tome and Principe",
  "Saudi Arabia",
  "Senegal",
  "Serbia",
  "Seychelles",
  "Scotland",
  "Sierra Leone",
  "Singapore",
  "Sint Maarten (Dutch part)",
  "Slovakia",
  "Slovenia",
  "Solomon Islands",
  "Somalia",
  "South Africa",
  "South Georgia and the South Sandwich Islands",
  "South Sudan",
  "Spain",
  "Sri Lanka",
  "Sudan",
  "Suriname",
  "Svalbard and Jan Mayen",
  "Sweden",
  "Switzerland",
  "Syrian Arab Republic",
  "Taiwan",
  "Tajikistan",
  "Tanzania, United Republic of",
  "Thailand",
  "Timor-Leste",
  "Togo",
  "Tokelau",
  "Tonga",
  "Trinidad and Tobago",
  "Tunisia",
  "Turkey",
  "Turkmenistan",
  "Turks and Caicos Islands",
  "Tuvalu",
  "Uganda",
  "Ukraine",
  "United Arab Emirates",
  "United Kingdom of Great Britain and Northern Ireland",
  "United States Minor Outlying Islands",
  "United States of America",
  "Uruguay",
  "Uzbekistan",
  "Vanuatu",
  "Venezuela (Bolivarian Republic of)",
  "Viet Nam",
  "Virgin Islands (British)",
  "Virgin Islands (U.S.)",
  "Wallis and Futuna",
  "Western Sahara",
  "Yemen",
  "Zambia",
  "Zimbabwe",
  "Åland Islands",
] as const;

export const MAJOR_COUNTRIES = [
  "Scotland",
  "United States of America",
  "Canada",
  "Ireland",
  "Japan",
] as const;

export const CATEGORY_LIST = [
  "blend",
  "bourbon",
  "rye",
  "single_grain",
  "single_malt",
  "single_pot_still",
  "spirit",
] as const;

export const SERVING_STYLE_LIST = ["neat", "rocks", "splash"] as const;

export const STORE_TYPE_LIST = [
  "astorwines",
  "healthyspirits",
  "totalwines",
  "woodencork",
] as const;

export const ENTITY_TYPE_LIST = ["brand", "bottler", "distiller"] as const;

export const BADGE_TYPE_LIST = ["bottle", "region", "category"] as const;

// https://whiskeytrends.com/whiskey-tasting-terminology/
// https://www.bonigala.com/25-ways-to-describe-whisky
export const DEFAULT_TAGS = [
  "acidic",
  "alcohol burn",
  "almond",
  "anise",
  "apple",
  "astringent",
  "balanced",
  "bananas",
  "berry",
  "biscuits",
  "bitter",
  "black pepper",
  "bland",
  "bread",
  "brine",
  "burnt",
  "butter",
  "butter",
  "butterscotch",
  "cake",
  "campfire",
  "candied cherries",
  "candy",
  "caramel",
  "cask",
  "cedar",
  "cereal",
  "charcoal",
  "charred",
  "cherry",
  "cherry",
  "chocolate",
  "cigar box",
  "cinnamon",
  "citrus",
  "clean",
  "clean",
  "clover",
  "cloves",
  "cocoa",
  "coconut",
  "coffee",
  "complex",
  "cookies",
  "course",
  "craisins",
  "cranberry",
  "creamy",
  "creosote",
  "currant",
  "cut grass",
  "dates",
  "dried apricots",
  "dried fruit",
  "dry",
  "dry",
  "earth",
  "esters",
  "ethanol",
  "eucalyptus",
  "fatty",
  "fatty",
  "fen",
  "fiery",
  "figs",
  "fireplace",
  "flat",
  "flowery",
  "fragrant",
  "fresh",
  "fresh fruit",
  "fruit cake",
  "fruity",
  "full-bodied",
  "grain",
  "grassy",
  "greasy",
  "greasy",
  "green",
  "green apple",
  "hard",
  "harsh",
  "hay",
  "heath",
  "heather",
  "heavy",
  "heavy",
  "herbal",
  "honey",
  "hot",
  "iodine",
  "kelp",
  "kippers",
  "lasting",
  "laurel",
  "leafy",
  "leather",
  "lemon",
  "light",
  "lime",
  "liqueur",
  "long",
  "malted milk",
  "malty",
  "maple",
  "marshmallow",
  "meadow",
  "medicinal",
  "mellow",
  "melon",
  "molasses",
  "moor",
  "moss",
  "musty",
  "neutral",
  "nuanced",
  "nutmeg",
  "nutty",
  "oak",
  "oatmeal",
  "ocean",
  "oily",
  "oily",
  "oloroso",
  "orange",
  "peach",
  "pear",
  "peat",
  "perfume",
  "phenolic",
  "pine",
  "pipe tobacco",
  "plum",
  "port",
  "prunes",
  "raisins",
  "red wine",
  "resin",
  "rich",
  "rich",
  "robust",
  "rope",
  "rose petals",
  "rosewater",
  "round",
  "rum",
  "salt",
  "sap",
  "savory",
  "seaside",
  "seaweed",
  "sharp",
  "sherry",
  "short",
  "shortbread",
  "silage",
  "smoke",
  "smooth",
  "soft",
  "solvent",
  "spiced",
  "spicy",
  "spirity",
  "subtle",
  "sulphuric",
  "sweet",
  "sweet",
  "syrup",
  "tannic",
  "tar",
  "tarry rope",
  "tart",
  "tart",
  "tea",
  "thin",
  "toast",
  "tobacco",
  "toffee",
  "turpentine",
  "vanilla",
  "vegetal",
  "violets",
  "walnuts",
  "warmth",
  "wet dog",
  "wine",
  "woody",
  "zesty",
] as const;
