packages:
  - 'packages/*'
  - 'apps/*'
  - '!**/test/**'

catalog:
  drizzle-kit: ^0.23.0
  drizzle-orm: ^0.32.0
  eslint: ^8.57.0
  "@fontsource/raleway": ^5.0.19
  jsx-email: ^1.10.11
  pg: ^8.12.0
  prettier: ^3.3.2
  "@sentry/core": ^8.16.0
  "@sentry/nextjs": ^8.16.0
  "@sentry/node": ^8.16.0
  "@sentry/utils": ^8.16.0
  "@spotlightjs/spotlight": ^2.1.1
  superjson: ^2.2.1
  tailwindcss: ^3.4.1
  "@tailwindcss/forms": ^0.5.7
  "@tailwindcss/typography": ^0.5.12
  "prettier-plugin-tailwindcss": ^0.5.13
  "@tanstack/react-query": ^5.48.0
  "@tanstack/react-query-next-experimental": ^5.48.0
  "@trpc/client": 11.0.0-rc.461
  "@trpc/next": 11.0.0-rc.461
  "@trpc/react-query": 11.0.0-rc.461
  "@trpc/server": 11.0.0-rc.461
  tsx: ^4.16.2
  typescript: ^5.5.4
  "@types/node": ^20.14.9
  "@types/pg": ^8.11.6
  vitest: "~2.1.1"
  "vite-tsconfig-paths": "^5.0.1"
  zod: ^3.23.8

  react: ^18.2.0
  react-dom: ^18.2.0
  react-native: ^0.74.3
  "@types/react": ^18.2.0
  "@types/react-dom": ^18.2.0

catalogs:
  react19:
    react: 19.0.0-rc-8b08e99e-20240713
    react-dom: 19.0.0-rc-8b08e99e-20240713
    react-native: 0.75.0-rc.5
    "@types/react": ^18.3.3
    "@types/react-dom": ^18.3.0
