packages:
  - 'packages/*'
  - 'apps/*'
  - '!**/test/**'

catalog:
  eslint: ^9.6.0
  prettier: ^3.3.2
  typescript: ^5.5.3
  tailwindcss: ^3.4.1
  zod: ^3.23.8

# catalogs:
#   react18:
#     react: 18.3.1
#     react-dom: 18.3.1
#     "@types/react": ^18.3.3
#     "@types/react-dom": ^18.3.0
