packages:
  - 'packages/*'
  - 'apps/*'
  - '!**/test/**'

catalog:
  eslint: ^9.6.0
  prettier: ^3.3.2
  typescript: ^5.5.3
  tailwindcss: ^3.4.1
  zod: ^3.23.8

catalogs:
  react19:
    react: 19.0.0-rc-8b08e99e-20240713
    react-dom: 19.0.0-rc-8b08e99e-20240713
    react-native: 0.75.0-rc.5
    "@types/react": ^18.3.3
    "@types/react-dom": ^18.3.0

  react18:
    react: 18.3.1
    react-dom: 18.3.1
    react-native: 0.74.3
    "@types/react": ^18.3.3
    "@types/react-dom": ^18.3.0
