packages:
  - 'packages/*'
  - 'apps/*'
  - '!**/test/**'

catalog:
  drizzle-kit: ^0.30.5
  drizzle-orm: ^0.39.3
  eslint: ^8.57.0
  "@fontsource/raleway": ^5.0.19
  jsx-email: ^1.10.11
  pg: ^8.13.0
  prettier: ^3.3.2
  "@sentry/core": 9.6.0-alpha.0
  "@sentry/nextjs": 9.6.0-alpha.0
  "@sentry/node": 9.6.0-alpha.0
  "@spotlightjs/spotlight": ^2.1.1
  superjson: ^2.2.1
  tailwindcss: ^3.4.1
  "@tailwindcss/forms": ^0.5.7
  "@tailwindcss/typography": ^0.5.12
  "prettier-plugin-tailwindcss": ^0.5.13
  "@tanstack/react-query": ^5.48.0
  "@tanstack/react-query-next-experimental": ^5.48.0
  "@trpc/client": 11.0.0-rc.461
  "@trpc/next": 11.0.0-rc.461
  "@trpc/react-query": 11.0.0-rc.461
  "@trpc/server": 11.0.0-rc.461
  tsx: ^4.16.2
  typescript: ^5.5.4
  "@types/node": ^22.13.1
  "@types/pg": ^8.11.6
  vitest: "~3"
  "@vitest/coverage-v8": "~3"
  "vite-tsconfig-paths": "^5.0.1"
  zod: ^3.23.8

  react: ^18.2.0
  react-dom: ^18.2.0
  "@types/react": ^18.2.0
  "@types/react-dom": ^18.2.0
