packages:
  - 'packages/*'
  - 'apps/*'
  - '!**/test/**'

catalog:
  drizzle-kit: ^0.23.0
  drizzle-orm: ^0.32.0
  eslint: ^9.6.0
  pg: ^8.12.0
  prettier: ^3.3.2
  "@sentry/core": ^8.16.0
  "@sentry/nextjs": ^8.16.0
  "@sentry/node": ^8.16.0
  "@sentry/utils": ^8.16.0
  tailwindcss: ^3.4.1
  "@trpc/client": 11.0.0-rc.334
  "@trpc/next": 11.0.0-rc.334
  "@trpc/react-query": 11.0.0-rc.334
  "@trpc/server": 11.0.0-rc.334
  tsx: ^4.16.0
  typescript: ^5.5.3
  zod: ^3.23.8

catalogs:
  react19:
    react: 19.0.0-rc-8b08e99e-20240713
    react-dom: 19.0.0-rc-8b08e99e-20240713
    react-native: 0.75.0-rc.5
    "@types/react": ^18.3.3
    "@types/react-dom": ^18.3.0

  react18:
    react: 18.3.1
    react-dom: 18.3.1
    react-native: 0.74.3
    "@types/react": ^18.3.3
    "@types/react-dom": ^18.3.0
