export const DEFAULT_CREATED_BY_ID = 1;

export const MAX_FILESIZE = 1048576 * 20;

export const XP_PER_LEVEL = 5;

export const COUNTRY_LIST = [
  "Afghanistan",
  "Albania",
  "Algeria",
  "American Samoa",
  "Andorra",
  "Angola",
  "Anguilla",
  "Antarctica",
  "Antigua and Barbuda",
  "Argentina",
  "Armenia",
  "Aruba",
  "Australia",
  "Austria",
  "Azerbaijan",
  "Bahamas",
  "Bahrain",
  "Bangladesh",
  "Barbados",
  "Belarus",
  "Belgium",
  "Belize",
  "Benin",
  "Bermuda",
  "Bhutan",
  "Bolivia (Plurinational State of)",
  "Bonaire, Sint Eustatius and Saba",
  "Bosnia and Herzegovina",
  "Botswana",
  "Bouvet Island",
  "Brazil",
  "British Indian Ocean Territory",
  "Brunei Darussalam",
  "Bulgaria",
  "Burkina Faso",
  "Burundi",
  "Cabo Verde",
  "Cambodia",
  "Cameroon",
  "Canada",
  "Cayman Islands",
  "Central African Republic",
  "Chad",
  "Chile",
  "China",
  "Christmas Island",
  "Cocos (Keeling) Islands",
  "Colombia",
  "Comoros",
  "Congo (the Democratic Republic of the)",
  "Congo",
  "Cook Islands",
  "Costa Rica",
  "Croatia",
  "Cuba",
  "Curaçao",
  "Cyprus",
  "Czechia",
  "Côte d'Ivoire",
  "Denmark",
  "Djibouti",
  "Dominica",
  "Dominican Republic",
  "Ecuador",
  "Egypt",
  "El Salvador",
  "Equatorial Guinea",
  "Eritrea",
  "Estonia",
  "Eswatini",
  "Ethiopia",
  "Falkland Islands (the) [Malvinas]",
  "Faroe Islands",
  "Fiji",
  "Finland",
  "France",
  "French Guiana",
  "French Polynesia",
  "French Southern Territories",
  "Gabon",
  "Gambia",
  "Georgia",
  "Germany",
  "Ghana",
  "Gibraltar",
  "Greece",
  "Greenland",
  "Grenada",
  "Guadeloupe",
  "Guam",
  "Guatemala",
  "Guernsey",
  "Guinea",
  "Guinea-Bissau",
  "Guyana",
  "Haiti",
  "Heard Island and McDonald Islands",
  "Holy See",
  "Honduras",
  "Hong Kong",
  "Hungary",
  "Iceland",
  "India",
  "Indonesia",
  "Iran (Islamic Republic of)",
  "Iraq",
  "Ireland",
  "Isle of Man",
  "Israel",
  "Italy",
  "Jamaica",
  "Japan",
  "Jersey",
  "Jordan",
  "Kazakhstan",
  "Kenya",
  "Kiribati",
  "Korea (the Democratic People's Republic of)",
  "Korea (the Republic of)",
  "Kuwait",
  "Kyrgyzstan",
  "Lao People's Democratic Republic",
  "Latvia",
  "Lebanon",
  "Lesotho",
  "Liberia",
  "Libya",
  "Liechtenstein",
  "Lithuania",
  "Luxembourg",
  "Macao",
  "Madagascar",
  "Malawi",
  "Malaysia",
  "Maldives",
  "Mali",
  "Malta",
  "Marshall Islands",
  "Martinique",
  "Mauritania",
  "Mauritius",
  "Mayotte",
  "Mexico",
  "Micronesia (Federated States of)",
  "Moldova (the Republic of)",
  "Monaco",
  "Mongolia",
  "Montenegro",
  "Montserrat",
  "Morocco",
  "Mozambique",
  "Myanmar",
  "Namibia",
  "Nauru",
  "Nepal",
  "Netherlands",
  "New Caledonia",
  "New Zealand",
  "Nicaragua",
  "Niger",
  "Nigeria",
  "Niue",
  "Norfolk Island",
  "Northern Mariana Islands",
  "Norway",
  "Oman",
  "Pakistan",
  "Palau",
  "Palestine, State of",
  "Panama",
  "Papua New Guinea",
  "Paraguay",
  "Peru",
  "Philippines",
  "Pitcairn",
  "Poland",
  "Portugal",
  "Puerto Rico",
  "Qatar",
  "Republic of North Macedonia",
  "Romania",
  "Russian Federation",
  "Rwanda",
  "Réunion",
  "Saint Barthélemy",
  "Saint Helena, Ascension and Tristan da Cunha",
  "Saint Kitts and Nevis",
  "Saint Lucia",
  "Saint Martin (French part)",
  "Saint Pierre and Miquelon",
  "Saint Vincent and the Grenadines",
  "Samoa",
  "San Marino",
  "Sao Tome and Principe",
  "Saudi Arabia",
  "Senegal",
  "Serbia",
  "Seychelles",
  "Scotland",
  "Sierra Leone",
  "Singapore",
  "Sint Maarten (Dutch part)",
  "Slovakia",
  "Slovenia",
  "Solomon Islands",
  "Somalia",
  "South Africa",
  "South Georgia and the South Sandwich Islands",
  "South Sudan",
  "Spain",
  "Sri Lanka",
  "Sudan",
  "Suriname",
  "Svalbard and Jan Mayen",
  "Sweden",
  "Switzerland",
  "Syrian Arab Republic",
  "Taiwan",
  "Tajikistan",
  "Tanzania, United Republic of",
  "Thailand",
  "Timor-Leste",
  "Togo",
  "Tokelau",
  "Tonga",
  "Trinidad and Tobago",
  "Tunisia",
  "Turkey",
  "Turkmenistan",
  "Turks and Caicos Islands",
  "Tuvalu",
  "Uganda",
  "Ukraine",
  "United Arab Emirates",
  "United Kingdom of Great Britain and Northern Ireland",
  "United States Minor Outlying Islands",
  "United States of America",
  "Uruguay",
  "Uzbekistan",
  "Vanuatu",
  "Venezuela (Bolivarian Republic of)",
  "Viet Nam",
  "Virgin Islands (British)",
  "Virgin Islands (U.S.)",
  "Wallis and Futuna",
  "Western Sahara",
  "Yemen",
  "Zambia",
  "Zimbabwe",
  "Åland Islands",
] as const;

export const MAJOR_COUNTRIES = [
  "Scotland",
  "United States of America",
  "Canada",
  "Ireland",
  "Japan",
] as const;

export const CATEGORY_LIST = [
  "blend",
  "bourbon",
  "rye",
  "single_grain",
  "single_malt",
  "single_pot_still",
  "spirit",
] as const;

export const SERVING_STYLE_LIST = ["neat", "rocks", "splash"] as const;

export const EXTERNAL_SITE_TYPE_LIST = [
  "astorwines",
  "healthyspirits",
  "smws",
  "smwsa",
  "totalwine",
  "woodencork",
  "whiskyadvocate",
] as const;

export const ENTITY_TYPE_LIST = ["brand", "bottler", "distiller"] as const;

export const BADGE_TYPE_LIST = ["bottle", "region", "category"] as const;

// https://whiskeytrends.com/whiskey-tasting-terminology/
// https://www.bonigala.com/25-ways-to-describe-whisky

export const FLAVOR_PROFILES = [
  "young_spritely",
  "sweet_fruit_mellow",
  "spicy_sweet",
  "spicy_dry",
  "deep_rich_dried_fruit",
  "old_dignified",
  "light_delicate",
  "juicy_oak_vanilla",
  "oily_coastal",
  "lightly_peated",
  "peated",
  "heavily_peated",
] as const;

// TODO: maybe utilize https://www.whiskymax.co.uk/charles-macleans-whisky-wheel/
// instead? its a bit easier to reason about for
export const TAG_CATEGORIES = [
  "cereal",
  "fruity",
  "floral",
  "peaty",
  "feinty",
  "sulphury",
  "woody",
  "winey",
] as const;

// TODO: reference whisky magazine for numerical, but simplify
export const COLOR_SCALE = [
  [0, "Clear", "#ffffff"],
  [1, "White Wine", "#fffbe0"],
  [2, "Melon Yellow", "#fdeda2"],
  [3, "Fine Sherry", "#faea8a"],
  [4, "Pale Honey", "#f7e07a"],
  [5, "Pale Gold", "#f5db6d"],
  [6, "Medium Gold", "#f5d863"],
  [7, "Deep Gold", "#f0ce62"],
  [8, "Amontillado Sherry", "#f0c962"],
  [9, "Pale Brown", "#efc358"],
  [10, "Medium Brown", "#efbf50"],
  [11, "Deep Brown", "#e0ae3d"],
  [12, "Palo Coratdo Sherry", "#dea03d"],
  [13, "Burn Amber", "#da9635"],
  [14, "Copper", "#cf7831"],
  [15, "Tawny", "#d06c3a"],
  [16, "Deep Tawhny", "#bf573a"],
  [17, "Oloroso Sherry", "#a23a2f"],
  [18, "Vintage Oak", "#932e24"],
  [19, "Moscatel Sherry", "#6a3022"],
  [20, "Black Bowmore", "#3b1d12"],
] as const;

// TODO:
export const CASK_FILLS = ["1st_fill", "2nd_fill", "refill"];

// TODO: determine granularity (e.g. hogshead etc)
export const CASK_TYPES = ["bourbon", "sherry", "other"] as const;

// used for web scraping
export const defaultHeaders = (url: string) => {
  const urlParts = new URL(url);
  return {
    Authority: urlParts.hostname,
    "User-Agent":
      "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/114.0.0.0 Safari/537.36",
    Accept:
      "text/html,application/xhtml+xml,application/xml;q=0.9,image/avif,image/webp,image/apng,*/*;q=0.8,application/signed-exchange;v=b3;q=0.7,",
    "Accept-Language": "en-US,en:q=0.9",
    Referer: urlParts.origin,
  };
};
