INSERT INTO country (name, slug) VALUES('Afghanistan', 'afghanistan');
INSERT INTO country (name, slug) VALUES('Albania', 'albania');
INSERT INTO country (name, slug) VALUES('Algeria', 'algeria');
INSERT INTO country (name, slug) VALUES('American Samoa', 'american-samoa');
INSERT INTO country (name, slug) VALUES('Andorra', 'andorra');
INSERT INTO country (name, slug) VALUES('Angola', 'angola');
INSERT INTO country (name, slug) VALUES('Anguilla', 'anguilla');
INSERT INTO country (name, slug) VALUES('Antarctica', 'antarctica');
INSERT INTO country (name, slug) VALUES('Antigua and Barbuda', 'antigua-and-barbuda');
INSERT INTO country (name, slug) VALUES('Argentina', 'argentina');
INSERT INTO country (name, slug) VALUES('Armenia', 'armenia');
INSERT INTO country (name, slug) VALUES('Aruba', 'aruba');
INSERT INTO country (name, slug) VALUES('Australia', 'australia');
INSERT INTO country (name, slug) VALUES('Austria', 'austria');
INSERT INTO country (name, slug) VALUES('Azerbaijan', 'azerbaijan');
INSERT INTO country (name, slug) VALUES('Bahamas', 'bahamas');
INSERT INTO country (name, slug) VALUES('Bahrain', 'bahrain');
INSERT INTO country (name, slug) VALUES('Bangladesh', 'bangladesh');
INSERT INTO country (name, slug) VALUES('Barbados', 'barbados');
INSERT INTO country (name, slug) VALUES('Belarus', 'belarus');
INSERT INTO country (name, slug) VALUES('Belgium', 'belgium');
INSERT INTO country (name, slug) VALUES('Belize', 'belize');
INSERT INTO country (name, slug) VALUES('Benin', 'benin');
INSERT INTO country (name, slug) VALUES('Bermuda', 'bermuda');
INSERT INTO country (name, slug) VALUES('Bhutan', 'bhutan');
INSERT INTO country (name, slug) VALUES('Bolivia', 'bolivia');
INSERT INTO country (name, slug) VALUES('Bonaire, Sint Eustatius and Saba', 'bonaire-sint-eustatius-and-saba');
INSERT INTO country (name, slug) VALUES('Bosnia and Herzegovina', 'bosnia-and-herzegovina');
INSERT INTO country (name, slug) VALUES('Botswana', 'botswana');
INSERT INTO country (name, slug) VALUES('Bouvet Island', 'bouvet-island');
INSERT INTO country (name, slug) VALUES('Brazil', 'brazil');
INSERT INTO country (name, slug) VALUES('British Indian Ocean Territory', 'british-indian-ocean-territory');
INSERT INTO country (name, slug) VALUES('Brunei Darussalam', 'brunei-darussalam');
INSERT INTO country (name, slug) VALUES('Bulgaria', 'bulgaria');
INSERT INTO country (name, slug) VALUES('Burkina Faso', 'burkina-faso');
INSERT INTO country (name, slug) VALUES('Burundi', 'burundi');
INSERT INTO country (name, slug) VALUES('Cabo Verde', 'cabo-verde');
INSERT INTO country (name, slug) VALUES('Cambodia', 'cambodia');
INSERT INTO country (name, slug) VALUES('Cameroon', 'cameroon');
INSERT INTO country (name, slug) VALUES('Canada', 'canada');
INSERT INTO country (name, slug) VALUES('Cayman Islands', 'cayman-islands');
INSERT INTO country (name, slug) VALUES('Central African Republic', 'central-african-republic');
INSERT INTO country (name, slug) VALUES('Chad', 'chad');
INSERT INTO country (name, slug) VALUES('Chile', 'chile');
INSERT INTO country (name, slug) VALUES('China', 'china');
INSERT INTO country (name, slug) VALUES('Christmas Island', 'christmas-island');
INSERT INTO country (name, slug) VALUES('Cocos (Keeling) Islands', 'cocos-keeling-islands');
INSERT INTO country (name, slug) VALUES('Colombia', 'colombia');
INSERT INTO country (name, slug) VALUES('Comoros', 'comoros');
INSERT INTO country (name, slug) VALUES('Congo', 'congo');
INSERT INTO country (name, slug) VALUES('Cook Islands', 'cook-islands');
INSERT INTO country (name, slug) VALUES('Costa Rica', 'costa-rica');
INSERT INTO country (name, slug) VALUES('Croatia', 'croatia');
INSERT INTO country (name, slug) VALUES('Cuba', 'cuba');
INSERT INTO country (name, slug) VALUES('Curaçao', 'curaçao');
INSERT INTO country (name, slug) VALUES('Cyprus', 'cyprus');
INSERT INTO country (name, slug) VALUES('Czechia', 'czechia');
INSERT INTO country (name, slug) VALUES('Côte d''Ivoire', 'côte-divoire');
INSERT INTO country (name, slug) VALUES('Denmark', 'denmark');
INSERT INTO country (name, slug) VALUES('Djibouti', 'djibouti');
INSERT INTO country (name, slug) VALUES('Dominica', 'dominica');
INSERT INTO country (name, slug) VALUES('Dominican Republic', 'dominican-republic');
INSERT INTO country (name, slug) VALUES('Ecuador', 'ecuador');
INSERT INTO country (name, slug) VALUES('Egypt', 'egypt');
INSERT INTO country (name, slug) VALUES('El Salvador', 'el-salvador');
INSERT INTO country (name, slug) VALUES('Equatorial Guinea', 'equatorial-guinea');
INSERT INTO country (name, slug) VALUES('Eritrea', 'eritrea');
INSERT INTO country (name, slug) VALUES('Estonia', 'estonia');
INSERT INTO country (name, slug) VALUES('Eswatini', 'eswatini');
INSERT INTO country (name, slug) VALUES('Ethiopia', 'ethiopia');
INSERT INTO country (name, slug) VALUES('Falkland Islands', 'falkland-islands');
INSERT INTO country (name, slug) VALUES('Faroe Islands', 'faroe-islands');
INSERT INTO country (name, slug) VALUES('Fiji', 'fiji');
INSERT INTO country (name, slug) VALUES('Finland', 'finland');
INSERT INTO country (name, slug) VALUES('France', 'france');
INSERT INTO country (name, slug) VALUES('French Guiana', 'french-guiana');
INSERT INTO country (name, slug) VALUES('French Polynesia', 'french-polynesia');
INSERT INTO country (name, slug) VALUES('French Southern Territories', 'french-southern-territories');
INSERT INTO country (name, slug) VALUES('Gabon', 'gabon');
INSERT INTO country (name, slug) VALUES('Gambia', 'gambia');
INSERT INTO country (name, slug) VALUES('Georgia', 'georgia');
INSERT INTO country (name, slug) VALUES('Germany', 'germany');
INSERT INTO country (name, slug) VALUES('Ghana', 'ghana');
INSERT INTO country (name, slug) VALUES('Gibraltar', 'gibraltar');
INSERT INTO country (name, slug) VALUES('Greece', 'greece');
INSERT INTO country (name, slug) VALUES('Greenland', 'greenland');
INSERT INTO country (name, slug) VALUES('Grenada', 'grenada');
INSERT INTO country (name, slug) VALUES('Guadeloupe', 'guadeloupe');
INSERT INTO country (name, slug) VALUES('Guam', 'guam');
INSERT INTO country (name, slug) VALUES('Guatemala', 'guatemala');
INSERT INTO country (name, slug) VALUES('Guernsey', 'guernsey');
INSERT INTO country (name, slug) VALUES('Guinea', 'guinea');
INSERT INTO country (name, slug) VALUES('Guinea-Bissau', 'guinea-bissau');
INSERT INTO country (name, slug) VALUES('Guyana', 'guyana');
INSERT INTO country (name, slug) VALUES('Haiti', 'haiti');
INSERT INTO country (name, slug) VALUES('Heard Island and McDonald Islands', 'heard-island-and-mcdonald-islands');
INSERT INTO country (name, slug) VALUES('Holy See', 'holy-see');
INSERT INTO country (name, slug) VALUES('Honduras', 'honduras');
INSERT INTO country (name, slug) VALUES('Hong Kong', 'hong-kong');
INSERT INTO country (name, slug) VALUES('Hungary', 'hungary');
INSERT INTO country (name, slug) VALUES('Iceland', 'iceland');
INSERT INTO country (name, slug) VALUES('India', 'india');
INSERT INTO country (name, slug) VALUES('Indonesia', 'indonesia');
INSERT INTO country (name, slug) VALUES('Iran', 'iran');
INSERT INTO country (name, slug) VALUES('Iraq', 'iraq');
INSERT INTO country (name, slug) VALUES('Ireland', 'ireland');
INSERT INTO country (name, slug) VALUES('Isle of Man', 'isle-of-man');
INSERT INTO country (name, slug) VALUES('Israel', 'israel');
INSERT INTO country (name, slug) VALUES('Italy', 'italy');
INSERT INTO country (name, slug) VALUES('Jamaica', 'jamaica');
INSERT INTO country (name, slug) VALUES('Japan', 'japan');
INSERT INTO country (name, slug) VALUES('Jersey', 'jersey');
INSERT INTO country (name, slug) VALUES('Jordan', 'jordan');
INSERT INTO country (name, slug) VALUES('Kazakhstan', 'kazakhstan');
INSERT INTO country (name, slug) VALUES('Kenya', 'kenya');
INSERT INTO country (name, slug) VALUES('Kiribati', 'kiribati');
INSERT INTO country (name, slug) VALUES('South Korea', 'south-korea');
INSERT INTO country (name, slug) VALUES('North Korea', 'north-korea');
INSERT INTO country (name, slug) VALUES('Kuwait', 'kuwait');
INSERT INTO country (name, slug) VALUES('Kyrgyzstan', 'kyrgyzstan');
INSERT INTO country (name, slug) VALUES('Laos', 'laos');
INSERT INTO country (name, slug) VALUES('Latvia', 'latvia');
INSERT INTO country (name, slug) VALUES('Lebanon', 'lebanon');
INSERT INTO country (name, slug) VALUES('Lesotho', 'lesotho');
INSERT INTO country (name, slug) VALUES('Liberia', 'liberia');
INSERT INTO country (name, slug) VALUES('Libya', 'libya');
INSERT INTO country (name, slug) VALUES('Liechtenstein', 'liechtenstein');
INSERT INTO country (name, slug) VALUES('Lithuania', 'lithuania');
INSERT INTO country (name, slug) VALUES('Luxembourg', 'luxembourg');
INSERT INTO country (name, slug) VALUES('Macao', 'macao');
INSERT INTO country (name, slug) VALUES('Madagascar', 'madagascar');
INSERT INTO country (name, slug) VALUES('Malawi', 'malawi');
INSERT INTO country (name, slug) VALUES('Malaysia', 'malaysia');
INSERT INTO country (name, slug) VALUES('Maldives', 'maldives');
INSERT INTO country (name, slug) VALUES('Mali', 'mali');
INSERT INTO country (name, slug) VALUES('Malta', 'malta');
INSERT INTO country (name, slug) VALUES('Marshall Islands', 'marshall-islands');
INSERT INTO country (name, slug) VALUES('Martinique', 'martinique');
INSERT INTO country (name, slug) VALUES('Mauritania', 'mauritania');
INSERT INTO country (name, slug) VALUES('Mauritius', 'mauritius');
INSERT INTO country (name, slug) VALUES('Mayotte', 'mayotte');
INSERT INTO country (name, slug) VALUES('Mexico', 'mexico');
INSERT INTO country (name, slug) VALUES('Micronesia', 'micronesia');
INSERT INTO country (name, slug) VALUES('Moldova', 'moldova');
INSERT INTO country (name, slug) VALUES('Monaco', 'monaco');
INSERT INTO country (name, slug) VALUES('Mongolia', 'mongolia');
INSERT INTO country (name, slug) VALUES('Montenegro', 'montenegro');
INSERT INTO country (name, slug) VALUES('Montserrat', 'montserrat');
INSERT INTO country (name, slug) VALUES('Morocco', 'morocco');
INSERT INTO country (name, slug) VALUES('Mozambique', 'mozambique');
INSERT INTO country (name, slug) VALUES('Myanmar', 'myanmar');
INSERT INTO country (name, slug) VALUES('Namibia', 'namibia');
INSERT INTO country (name, slug) VALUES('Nauru', 'nauru');
INSERT INTO country (name, slug) VALUES('Nepal', 'nepal');
INSERT INTO country (name, slug) VALUES('Netherlands', 'netherlands');
INSERT INTO country (name, slug) VALUES('New Caledonia', 'new-caledonia');
INSERT INTO country (name, slug) VALUES('New Zealand', 'new-zealand');
INSERT INTO country (name, slug) VALUES('Nicaragua', 'nicaragua');
INSERT INTO country (name, slug) VALUES('Niger', 'niger');
INSERT INTO country (name, slug) VALUES('Nigeria', 'nigeria');
INSERT INTO country (name, slug) VALUES('Niue', 'niue');
INSERT INTO country (name, slug) VALUES('Norfolk Island', 'norfolk-island');
INSERT INTO country (name, slug) VALUES('Northern Mariana Islands', 'northern-mariana-islands');
INSERT INTO country (name, slug) VALUES('Norway', 'norway');
INSERT INTO country (name, slug) VALUES('Oman', 'oman');
INSERT INTO country (name, slug) VALUES('Pakistan', 'pakistan');
INSERT INTO country (name, slug) VALUES('Palau', 'palau');
INSERT INTO country (name, slug) VALUES('Palestine, State of', 'palestine-state-of');
INSERT INTO country (name, slug) VALUES('Panama', 'panama');
INSERT INTO country (name, slug) VALUES('Papua New Guinea', 'papua-new-guinea');
INSERT INTO country (name, slug) VALUES('Paraguay', 'paraguay');
INSERT INTO country (name, slug) VALUES('Peru', 'peru');
INSERT INTO country (name, slug) VALUES('Philippines', 'philippines');
INSERT INTO country (name, slug) VALUES('Pitcairn', 'pitcairn');
INSERT INTO country (name, slug) VALUES('Poland', 'poland');
INSERT INTO country (name, slug) VALUES('Portugal', 'portugal');
INSERT INTO country (name, slug) VALUES('Puerto Rico', 'puerto-rico');
INSERT INTO country (name, slug) VALUES('Qatar', 'qatar');
INSERT INTO country (name, slug) VALUES('Republic of North Macedonia', 'republic-of-north-macedonia');
INSERT INTO country (name, slug) VALUES('Romania', 'romania');
INSERT INTO country (name, slug) VALUES('Russian Federation', 'russian-federation');
INSERT INTO country (name, slug) VALUES('Rwanda', 'rwanda');
INSERT INTO country (name, slug) VALUES('Réunion', 'réunion');
INSERT INTO country (name, slug) VALUES('Saint Barthélemy', 'saint-barthelemy');
INSERT INTO country (name, slug) VALUES('Saint Helena, Ascension and Tristan da Cunha', 'saint-helena-ascension-and-tristan-da-cunha');
INSERT INTO country (name, slug) VALUES('Saint Kitts and Nevis', 'saint-kitts-and-nevis');
INSERT INTO country (name, slug) VALUES('Saint Lucia', 'saint-lucia');
INSERT INTO country (name, slug) VALUES('Saint Martin (French part)', 'saint-martin-french-part');
INSERT INTO country (name, slug) VALUES('Saint Pierre and Miquelon', 'saint-pierre-and-miquelon');
INSERT INTO country (name, slug) VALUES('Saint Vincent and the Grenadines', 'saint-vincent-and-the-grenadines');
INSERT INTO country (name, slug) VALUES('Samoa', 'samoa');
INSERT INTO country (name, slug) VALUES('San Marino', 'san-marino');
INSERT INTO country (name, slug) VALUES('Sao Tome and Principe', 'sao-tome-and-principe');
INSERT INTO country (name, slug) VALUES('Saudi Arabia', 'saudi-arabia');
INSERT INTO country (name, slug) VALUES('Senegal', 'senegal');
INSERT INTO country (name, slug) VALUES('Serbia', 'serbia');
INSERT INTO country (name, slug) VALUES('Seychelles', 'seychelles');
INSERT INTO country (name, slug) VALUES('Scotland', 'scotland');
INSERT INTO country (name, slug) VALUES('Sierra Leone', 'sierra-leone');
INSERT INTO country (name, slug) VALUES('Singapore', 'singapore');
INSERT INTO country (name, slug) VALUES('Sint Maarten', 'sint-maarten');
INSERT INTO country (name, slug) VALUES('Slovakia', 'slovakia');
INSERT INTO country (name, slug) VALUES('Slovenia', 'slovenia');
INSERT INTO country (name, slug) VALUES('Solomon Islands', 'solomon-islands');
INSERT INTO country (name, slug) VALUES('Somalia', 'somalia');
INSERT INTO country (name, slug) VALUES('South Africa', 'south-africa');
INSERT INTO country (name, slug) VALUES('South Georgia and the South Sandwich Islands', 'south-georgia-and-the-south-sandwich-islands');
INSERT INTO country (name, slug) VALUES('South Sudan', 'south-sudan');
INSERT INTO country (name, slug) VALUES('Spain', 'spain');
INSERT INTO country (name, slug) VALUES('Sri Lanka', 'sri-lanka');
INSERT INTO country (name, slug) VALUES('Sudan', 'sudan');
INSERT INTO country (name, slug) VALUES('Suriname', 'suriname');
INSERT INTO country (name, slug) VALUES('Svalbard and Jan Mayen', 'svalbard-and-jan-mayen');
INSERT INTO country (name, slug) VALUES('Sweden', 'sweden');
INSERT INTO country (name, slug) VALUES('Switzerland', 'switzerland');
INSERT INTO country (name, slug) VALUES('Syrian Arab Republic', 'syrian-arab-republic');
INSERT INTO country (name, slug) VALUES('Taiwan', 'taiwan');
INSERT INTO country (name, slug) VALUES('Tajikistan', 'tajikistan');
INSERT INTO country (name, slug) VALUES('Tanzania', 'tanzania');
INSERT INTO country (name, slug) VALUES('Thailand', 'thailand');
INSERT INTO country (name, slug) VALUES('Timor-Leste', 'timor-leste');
INSERT INTO country (name, slug) VALUES('Togo', 'togo');
INSERT INTO country (name, slug) VALUES('Tokelau', 'tokelau');
INSERT INTO country (name, slug) VALUES('Tonga', 'tonga');
INSERT INTO country (name, slug) VALUES('Trinidad and Tobago', 'trinidad-and-tobago');
INSERT INTO country (name, slug) VALUES('Tunisia', 'tunisia');
INSERT INTO country (name, slug) VALUES('Turkey', 'turkey');
INSERT INTO country (name, slug) VALUES('Turkmenistan', 'turkmenistan');
INSERT INTO country (name, slug) VALUES('Turks and Caicos Islands', 'turks-and-caicos-islands');
INSERT INTO country (name, slug) VALUES('Tuvalu', 'tuvalu');
INSERT INTO country (name, slug) VALUES('Uganda', 'uganda');
INSERT INTO country (name, slug) VALUES('Ukraine', 'ukraine');
INSERT INTO country (name, slug) VALUES('United Arab Emirates', 'united-arab-emirates');
INSERT INTO country (name, slug) VALUES('United Kingdom', 'united-kingdom');
INSERT INTO country (name, slug) VALUES('United States Minor Outlying Islands', 'united-states-minor-outlying-islands');
INSERT INTO country (name, slug) VALUES('United States of America', 'united-states');
INSERT INTO country (name, slug) VALUES('Uruguay', 'uruguay');
INSERT INTO country (name, slug) VALUES('Uzbekistan', 'uzbekistan');
INSERT INTO country (name, slug) VALUES('Vanuatu', 'vanuatu');
INSERT INTO country (name, slug) VALUES('Venezuela', 'venezuela');
INSERT INTO country (name, slug) VALUES('Vietnam', 'vietnam');
INSERT INTO country (name, slug) VALUES('Virgin Islands', 'virgin-islands');
INSERT INTO country (name, slug) VALUES('Wallis and Futuna', 'wallis-and-futuna');
INSERT INTO country (name, slug) VALUES('Western Sahara', 'western-sahara');
INSERT INTO country (name, slug) VALUES('Yemen', 'yemen');
INSERT INTO country (name, slug) VALUES('Zambia', 'zambia');
INSERT INTO country (name, slug) VALUES('Zimbabwe', 'zimbabwe');
INSERT INTO country (name, slug) VALUES('Åland Islands', 'aland-islands');
