ALTER TABLE "country" ADD COLUMN "alpha2" char(2);

UPDATE country SET name = 'United States' WHERE name = 'United States of America';

UPDATE country SET alpha2 = 'AF' WHERE name = 'Afghanistan';
UPDATE country SET alpha2 = 'AX' WHERE name = 'Åland Islands';
UPDATE country SET alpha2 = 'AL' WHERE name = 'Albania';
UPDATE country SET alpha2 = 'DZ' WHERE name = 'Algeria';
UPDATE country SET alpha2 = 'AS' WHERE name = 'American Samoa';
UPDATE country SET alpha2 = 'AD' WHERE name = 'Andorra';
UPDATE country SET alpha2 = 'AO' WHERE name = 'Angola';
UPDATE country SET alpha2 = 'AI' WHERE name = 'Anguilla';
UPDATE country SET alpha2 = 'AQ' WHERE name = 'Antarctica';
UPDATE country SET alpha2 = 'AG' WHERE name = 'Antigua and Barbuda';
UPDATE country SET alpha2 = 'AR' WHERE name = 'Argentina';
UPDATE country SET alpha2 = 'AM' WHERE name = 'Armenia';
UPDATE country SET alpha2 = 'AW' WHERE name = 'Aruba';
UPDATE country SET alpha2 = 'AU' WHERE name = 'Australia';
UPDATE country SET alpha2 = 'AT' WHERE name = 'Austria';
UPDATE country SET alpha2 = 'AZ' WHERE name = 'Azerbaijan';
UPDATE country SET alpha2 = 'BS' WHERE name = 'Bahamas';
UPDATE country SET alpha2 = 'BH' WHERE name = 'Bahrain';
UPDATE country SET alpha2 = 'BD' WHERE name = 'Bangladesh';
UPDATE country SET alpha2 = 'BB' WHERE name = 'Barbados';
UPDATE country SET alpha2 = 'BY' WHERE name = 'Belarus';
UPDATE country SET alpha2 = 'BE' WHERE name = 'Belgium';
UPDATE country SET alpha2 = 'BZ' WHERE name = 'Belize';
UPDATE country SET alpha2 = 'BJ' WHERE name = 'Benin';
UPDATE country SET alpha2 = 'BM' WHERE name = 'Bermuda';
UPDATE country SET alpha2 = 'BT' WHERE name = 'Bhutan';
UPDATE country SET alpha2 = 'BO' WHERE name = 'Bolivia, Plurinational State of';
UPDATE country SET alpha2 = 'BQ' WHERE name = 'Bonaire, Sint Eustatius and Saba';
UPDATE country SET alpha2 = 'BA' WHERE name = 'Bosnia and Herzegovina';
UPDATE country SET alpha2 = 'BW' WHERE name = 'Botswana';
UPDATE country SET alpha2 = 'BV' WHERE name = 'Bouvet Island';
UPDATE country SET alpha2 = 'BR' WHERE name = 'Brazil';
UPDATE country SET alpha2 = 'IO' WHERE name = 'British Indian Ocean Territory';
UPDATE country SET alpha2 = 'BN' WHERE name = 'Brunei Darussalam';
UPDATE country SET alpha2 = 'BG' WHERE name = 'Bulgaria';
UPDATE country SET alpha2 = 'BF' WHERE name = 'Burkina Faso';
UPDATE country SET alpha2 = 'BI' WHERE name = 'Burundi';
UPDATE country SET alpha2 = 'CV' WHERE name = 'Cabo Verde';
UPDATE country SET alpha2 = 'KH' WHERE name = 'Cambodia';
UPDATE country SET alpha2 = 'CM' WHERE name = 'Cameroon';
UPDATE country SET alpha2 = 'CA' WHERE name = 'Canada';
UPDATE country SET alpha2 = 'KY' WHERE name = 'Cayman Islands';
UPDATE country SET alpha2 = 'CF' WHERE name = 'Central African Republic';
UPDATE country SET alpha2 = 'TD' WHERE name = 'Chad';
UPDATE country SET alpha2 = 'CL' WHERE name = 'Chile';
UPDATE country SET alpha2 = 'CN' WHERE name = 'China';
UPDATE country SET alpha2 = 'CX' WHERE name = 'Christmas Island';
UPDATE country SET alpha2 = 'CC' WHERE name = 'Cocos (Keeling) Islands';
UPDATE country SET alpha2 = 'CO' WHERE name = 'Colombia';
UPDATE country SET alpha2 = 'KM' WHERE name = 'Comoros';
UPDATE country SET alpha2 = 'CG' WHERE name = 'Congo';
UPDATE country SET alpha2 = 'CD' WHERE name = 'Congo, Democratic Republic of the';
UPDATE country SET alpha2 = 'CK' WHERE name = 'Cook Islands';
UPDATE country SET alpha2 = 'CR' WHERE name = 'Costa Rica';
UPDATE country SET alpha2 = 'CI' WHERE name = 'Côte d''Ivoire';
UPDATE country SET alpha2 = 'HR' WHERE name = 'Croatia';
UPDATE country SET alpha2 = 'CU' WHERE name = 'Cuba';
UPDATE country SET alpha2 = 'CW' WHERE name = 'Curaçao';
UPDATE country SET alpha2 = 'CY' WHERE name = 'Cyprus';
UPDATE country SET alpha2 = 'CZ' WHERE name = 'Czechia';
UPDATE country SET alpha2 = 'DK' WHERE name = 'Denmark';
UPDATE country SET alpha2 = 'DJ' WHERE name = 'Djibouti';
UPDATE country SET alpha2 = 'DM' WHERE name = 'Dominica';
UPDATE country SET alpha2 = 'DO' WHERE name = 'Dominican Republic';
UPDATE country SET alpha2 = 'EC' WHERE name = 'Ecuador';
UPDATE country SET alpha2 = 'EG' WHERE name = 'Egypt';
UPDATE country SET alpha2 = 'SV' WHERE name = 'El Salvador';
UPDATE country SET alpha2 = 'GQ' WHERE name = 'Equatorial Guinea';
UPDATE country SET alpha2 = 'ER' WHERE name = 'Eritrea';
UPDATE country SET alpha2 = 'EE' WHERE name = 'Estonia';
UPDATE country SET alpha2 = 'SZ' WHERE name = 'Eswatini';
UPDATE country SET alpha2 = 'ET' WHERE name = 'Ethiopia';
UPDATE country SET alpha2 = 'FK' WHERE name = 'Falkland Islands (Malvinas)';
UPDATE country SET alpha2 = 'FO' WHERE name = 'Faroe Islands';
UPDATE country SET alpha2 = 'FJ' WHERE name = 'Fiji';
UPDATE country SET alpha2 = 'FI' WHERE name = 'Finland';
UPDATE country SET alpha2 = 'FR' WHERE name = 'France';
UPDATE country SET alpha2 = 'GF' WHERE name = 'French Guiana';
UPDATE country SET alpha2 = 'PF' WHERE name = 'French Polynesia';
UPDATE country SET alpha2 = 'TF' WHERE name = 'French Southern Territories';
UPDATE country SET alpha2 = 'GA' WHERE name = 'Gabon';
UPDATE country SET alpha2 = 'GM' WHERE name = 'Gambia';
UPDATE country SET alpha2 = 'GE' WHERE name = 'Georgia';
UPDATE country SET alpha2 = 'DE' WHERE name = 'Germany';
UPDATE country SET alpha2 = 'GH' WHERE name = 'Ghana';
UPDATE country SET alpha2 = 'GI' WHERE name = 'Gibraltar';
UPDATE country SET alpha2 = 'GR' WHERE name = 'Greece';
UPDATE country SET alpha2 = 'GL' WHERE name = 'Greenland';
UPDATE country SET alpha2 = 'GD' WHERE name = 'Grenada';
UPDATE country SET alpha2 = 'GP' WHERE name = 'Guadeloupe';
UPDATE country SET alpha2 = 'GU' WHERE name = 'Guam';
UPDATE country SET alpha2 = 'GT' WHERE name = 'Guatemala';
UPDATE country SET alpha2 = 'GG' WHERE name = 'Guernsey';
UPDATE country SET alpha2 = 'GN' WHERE name = 'Guinea';
UPDATE country SET alpha2 = 'GW' WHERE name = 'Guinea-Bissau';
UPDATE country SET alpha2 = 'GY' WHERE name = 'Guyana';
UPDATE country SET alpha2 = 'HT' WHERE name = 'Haiti';
UPDATE country SET alpha2 = 'HM' WHERE name = 'Heard Island and McDonald Islands';
UPDATE country SET alpha2 = 'VA' WHERE name = 'Holy See';
UPDATE country SET alpha2 = 'HN' WHERE name = 'Honduras';
UPDATE country SET alpha2 = 'HK' WHERE name = 'Hong Kong';
UPDATE country SET alpha2 = 'HU' WHERE name = 'Hungary';
UPDATE country SET alpha2 = 'IS' WHERE name = 'Iceland';
UPDATE country SET alpha2 = 'IN' WHERE name = 'India';
UPDATE country SET alpha2 = 'ID' WHERE name = 'Indonesia';
UPDATE country SET alpha2 = 'IR' WHERE name = 'Iran, Islamic Republic of';
UPDATE country SET alpha2 = 'IQ' WHERE name = 'Iraq';
UPDATE country SET alpha2 = 'IE' WHERE name = 'Ireland';
UPDATE country SET alpha2 = 'IM' WHERE name = 'Isle of Man';
UPDATE country SET alpha2 = 'IL' WHERE name = 'Israel';
UPDATE country SET alpha2 = 'IT' WHERE name = 'Italy';
UPDATE country SET alpha2 = 'JM' WHERE name = 'Jamaica';
UPDATE country SET alpha2 = 'JP' WHERE name = 'Japan';
UPDATE country SET alpha2 = 'JE' WHERE name = 'Jersey';
UPDATE country SET alpha2 = 'JO' WHERE name = 'Jordan';
UPDATE country SET alpha2 = 'KZ' WHERE name = 'Kazakhstan';
UPDATE country SET alpha2 = 'KE' WHERE name = 'Kenya';
UPDATE country SET alpha2 = 'KI' WHERE name = 'Kiribati';
UPDATE country SET alpha2 = 'KP' WHERE name = 'Korea, Democratic People''s Republic of';
UPDATE country SET alpha2 = 'KR' WHERE name = 'Korea, Republic of';
UPDATE country SET alpha2 = 'KW' WHERE name = 'Kuwait';
UPDATE country SET alpha2 = 'KG' WHERE name = 'Kyrgyzstan';
UPDATE country SET alpha2 = 'LA' WHERE name = 'Lao People''s Democratic Republic';
UPDATE country SET alpha2 = 'LV' WHERE name = 'Latvia';
UPDATE country SET alpha2 = 'LB' WHERE name = 'Lebanon';
UPDATE country SET alpha2 = 'LS' WHERE name = 'Lesotho';
UPDATE country SET alpha2 = 'LR' WHERE name = 'Liberia';
UPDATE country SET alpha2 = 'LY' WHERE name = 'Libya';
UPDATE country SET alpha2 = 'LI' WHERE name = 'Liechtenstein';
UPDATE country SET alpha2 = 'LT' WHERE name = 'Lithuania';
UPDATE country SET alpha2 = 'LU' WHERE name = 'Luxembourg';
UPDATE country SET alpha2 = 'MO' WHERE name = 'Macao';
UPDATE country SET alpha2 = 'MG' WHERE name = 'Madagascar';
UPDATE country SET alpha2 = 'MW' WHERE name = 'Malawi';
UPDATE country SET alpha2 = 'MY' WHERE name = 'Malaysia';
UPDATE country SET alpha2 = 'MV' WHERE name = 'Maldives';
UPDATE country SET alpha2 = 'ML' WHERE name = 'Mali';
UPDATE country SET alpha2 = 'MT' WHERE name = 'Malta';
UPDATE country SET alpha2 = 'MH' WHERE name = 'Marshall Islands';
UPDATE country SET alpha2 = 'MQ' WHERE name = 'Martinique';
UPDATE country SET alpha2 = 'MR' WHERE name = 'Mauritania';
UPDATE country SET alpha2 = 'MU' WHERE name = 'Mauritius';
UPDATE country SET alpha2 = 'YT' WHERE name = 'Mayotte';
UPDATE country SET alpha2 = 'MX' WHERE name = 'Mexico';
UPDATE country SET alpha2 = 'FM' WHERE name = 'Micronesia, Federated States of';
UPDATE country SET alpha2 = 'MD' WHERE name = 'Moldova, Republic of';
UPDATE country SET alpha2 = 'MC' WHERE name = 'Monaco';
UPDATE country SET alpha2 = 'MN' WHERE name = 'Mongolia';
UPDATE country SET alpha2 = 'ME' WHERE name = 'Montenegro';
UPDATE country SET alpha2 = 'MS' WHERE name = 'Montserrat';
UPDATE country SET alpha2 = 'MA' WHERE name = 'Morocco';
UPDATE country SET alpha2 = 'MZ' WHERE name = 'Mozambique';
UPDATE country SET alpha2 = 'MM' WHERE name = 'Myanmar';
UPDATE country SET alpha2 = 'NA' WHERE name = 'Namibia';
UPDATE country SET alpha2 = 'NR' WHERE name = 'Nauru';
UPDATE country SET alpha2 = 'NP' WHERE name = 'Nepal';
UPDATE country SET alpha2 = 'NL' WHERE name = 'Netherlands, Kingdom of the';
UPDATE country SET alpha2 = 'NC' WHERE name = 'New Caledonia';
UPDATE country SET alpha2 = 'NZ' WHERE name = 'New Zealand';
UPDATE country SET alpha2 = 'NI' WHERE name = 'Nicaragua';
UPDATE country SET alpha2 = 'NE' WHERE name = 'Niger';
UPDATE country SET alpha2 = 'NG' WHERE name = 'Nigeria';
UPDATE country SET alpha2 = 'NU' WHERE name = 'Niue';
UPDATE country SET alpha2 = 'NF' WHERE name = 'Norfolk Island';
UPDATE country SET alpha2 = 'MK' WHERE name = 'North Macedonia';
UPDATE country SET alpha2 = 'MP' WHERE name = 'Northern Mariana Islands';
UPDATE country SET alpha2 = 'NO' WHERE name = 'Norway';
UPDATE country SET alpha2 = 'OM' WHERE name = 'Oman';
UPDATE country SET alpha2 = 'PK' WHERE name = 'Pakistan';
UPDATE country SET alpha2 = 'PW' WHERE name = 'Palau';
UPDATE country SET alpha2 = 'PS' WHERE name = 'Palestine, State of';
UPDATE country SET alpha2 = 'PA' WHERE name = 'Panama';
UPDATE country SET alpha2 = 'PG' WHERE name = 'Papua New Guinea';
UPDATE country SET alpha2 = 'PY' WHERE name = 'Paraguay';
UPDATE country SET alpha2 = 'PE' WHERE name = 'Peru';
UPDATE country SET alpha2 = 'PH' WHERE name = 'Philippines';
UPDATE country SET alpha2 = 'PN' WHERE name = 'Pitcairn';
UPDATE country SET alpha2 = 'PL' WHERE name = 'Poland';
UPDATE country SET alpha2 = 'PT' WHERE name = 'Portugal';
UPDATE country SET alpha2 = 'PR' WHERE name = 'Puerto Rico';
UPDATE country SET alpha2 = 'QA' WHERE name = 'Qatar';
UPDATE country SET alpha2 = 'RE' WHERE name = 'Réunion';
UPDATE country SET alpha2 = 'RO' WHERE name = 'Romania';
UPDATE country SET alpha2 = 'RU' WHERE name = 'Russian Federation';
UPDATE country SET alpha2 = 'RW' WHERE name = 'Rwanda';
UPDATE country SET alpha2 = 'BL' WHERE name = 'Saint Barthélemy';
UPDATE country SET alpha2 = 'SH' WHERE name = 'Saint Helena, Ascension and Tristan da Cunha';
UPDATE country SET alpha2 = 'KN' WHERE name = 'Saint Kitts and Nevis';
UPDATE country SET alpha2 = 'LC' WHERE name = 'Saint Lucia';
UPDATE country SET alpha2 = 'MF' WHERE name = 'Saint Martin (French part)';
UPDATE country SET alpha2 = 'PM' WHERE name = 'Saint Pierre and Miquelon';
UPDATE country SET alpha2 = 'VC' WHERE name = 'Saint Vincent and the Grenadines';
UPDATE country SET alpha2 = 'WS' WHERE name = 'Samoa';
UPDATE country SET alpha2 = 'SM' WHERE name = 'San Marino';
UPDATE country SET alpha2 = 'ST' WHERE name = 'Sao Tome and Principe';
UPDATE country SET alpha2 = 'SA' WHERE name = 'Saudi Arabia';
UPDATE country SET alpha2 = 'SN' WHERE name = 'Senegal';
UPDATE country SET alpha2 = 'RS' WHERE name = 'Serbia';
UPDATE country SET alpha2 = 'SC' WHERE name = 'Seychelles';
UPDATE country SET alpha2 = 'SL' WHERE name = 'Sierra Leone';
UPDATE country SET alpha2 = 'SG' WHERE name = 'Singapore';
UPDATE country SET alpha2 = 'SX' WHERE name = 'Sint Maarten (Dutch part)';
UPDATE country SET alpha2 = 'SK' WHERE name = 'Slovakia';
UPDATE country SET alpha2 = 'SI' WHERE name = 'Slovenia';
UPDATE country SET alpha2 = 'SB' WHERE name = 'Solomon Islands';
UPDATE country SET alpha2 = 'SO' WHERE name = 'Somalia';
UPDATE country SET alpha2 = 'ZA' WHERE name = 'South Africa';
UPDATE country SET alpha2 = 'GS' WHERE name = 'South Georgia and the South Sandwich Islands';
UPDATE country SET alpha2 = 'SS' WHERE name = 'South Sudan';
UPDATE country SET alpha2 = 'ES' WHERE name = 'Spain';
UPDATE country SET alpha2 = 'LK' WHERE name = 'Sri Lanka';
UPDATE country SET alpha2 = 'SD' WHERE name = 'Sudan';
UPDATE country SET alpha2 = 'SR' WHERE name = 'Suriname';
UPDATE country SET alpha2 = 'SJ' WHERE name = 'Svalbard and Jan Mayen';
UPDATE country SET alpha2 = 'SE' WHERE name = 'Sweden';
UPDATE country SET alpha2 = 'CH' WHERE name = 'Switzerland';
UPDATE country SET alpha2 = 'SY' WHERE name = 'Syrian Arab Republic';
UPDATE country SET alpha2 = 'TW' WHERE name = 'Taiwan, Province of China';
UPDATE country SET alpha2 = 'TJ' WHERE name = 'Tajikistan';
UPDATE country SET alpha2 = 'TZ' WHERE name = 'Tanzania, United Republic of';
UPDATE country SET alpha2 = 'TH' WHERE name = 'Thailand';
UPDATE country SET alpha2 = 'TL' WHERE name = 'Timor-Leste';
UPDATE country SET alpha2 = 'TG' WHERE name = 'Togo';
UPDATE country SET alpha2 = 'TK' WHERE name = 'Tokelau';
UPDATE country SET alpha2 = 'TO' WHERE name = 'Tonga';
UPDATE country SET alpha2 = 'TT' WHERE name = 'Trinidad and Tobago';
UPDATE country SET alpha2 = 'TN' WHERE name = 'Tunisia';
UPDATE country SET alpha2 = 'TR' WHERE name = 'Türkiye';
UPDATE country SET alpha2 = 'TM' WHERE name = 'Turkmenistan';
UPDATE country SET alpha2 = 'TC' WHERE name = 'Turks and Caicos Islands';
UPDATE country SET alpha2 = 'TV' WHERE name = 'Tuvalu';
UPDATE country SET alpha2 = 'UG' WHERE name = 'Uganda';
UPDATE country SET alpha2 = 'UA' WHERE name = 'Ukraine';
UPDATE country SET alpha2 = 'AE' WHERE name = 'United Arab Emirates';
UPDATE country SET alpha2 = 'GB' WHERE name = 'United Kingdom of Great Britain and Northern Ireland';
UPDATE country SET alpha2 = 'US' WHERE name = 'United States of America';
UPDATE country SET alpha2 = 'UM' WHERE name = 'United States Minor Outlying Islands';
UPDATE country SET alpha2 = 'UY' WHERE name = 'Uruguay';
UPDATE country SET alpha2 = 'UZ' WHERE name = 'Uzbekistan';
UPDATE country SET alpha2 = 'VU' WHERE name = 'Vanuatu';
UPDATE country SET alpha2 = 'VE' WHERE name = 'Venezuela, Bolivarian Republic of';
UPDATE country SET alpha2 = 'VN' WHERE name = 'Viet Nam';
UPDATE country SET alpha2 = 'VG' WHERE name = 'Virgin Islands (British)';
UPDATE country SET alpha2 = 'VI' WHERE name = 'Virgin Islands (U.S.)';
UPDATE country SET alpha2 = 'WF' WHERE name = 'Wallis and Futuna';
UPDATE country SET alpha2 = 'EH' WHERE name = 'Western Sahara';
UPDATE country SET alpha2 = 'YE' WHERE name = 'Yemen';
UPDATE country SET alpha2 = 'ZM' WHERE name = 'Zambia';
UPDATE country SET alpha2 = 'ZW' WHERE name = 'Zimbabwe';
