ALTER TABLE "bottle_release_promotion" DISABLE ROW LEVEL SECURITY;
ALTER TABLE "bottle_release" DISABLE ROW LEVEL SECURITY;
ALTER TABLE "legacy_release_repair_review" DISABLE ROW LEVEL SECURITY;
DROP TABLE "bottle_release_promotion" CASCADE;
DROP TABLE "bottle_release" CASCADE;
DROP TABLE "legacy_release_repair_review" CASCADE;
ALTER TABLE "store_price_match_attempt" DROP CONSTRAINT "store_price_match_attempt_parent_bottle_id_bottle_id_fk";

ALTER TABLE "store_price_match_proposal" DROP CONSTRAINT "store_price_match_proposal_parent_bottle_id_bottle_id_fk";

DROP INDEX "bottle_alias_release_idx";
DROP INDEX "bottle_observation_release_idx";
DROP INDEX "collection_bottle_release_idx";
DROP INDEX "flight_bottle_release_idx";
DROP INDEX "incoming_bottle_decision_release_idx";
DROP INDEX "review_release_idx";
DROP INDEX "store_price_match_proposal_current_release_idx";
DROP INDEX "store_price_match_proposal_suggested_release_idx";
DROP INDEX "store_price_match_proposal_parent_bottle_idx";
DROP INDEX "store_price_release_idx";
DROP INDEX "tasting_release_idx";
ALTER TABLE "bottle_alias" DROP COLUMN "release_id";
ALTER TABLE "bottle_observation" DROP COLUMN "release_id";
ALTER TABLE "collection_bottle" DROP COLUMN "release_id";
ALTER TABLE "flight_bottle" DROP COLUMN "release_id";
ALTER TABLE "incoming_bottle_decision_log" DROP COLUMN "release_id";
ALTER TABLE "review" DROP COLUMN "release_id";
ALTER TABLE "store_price_match_attempt" DROP COLUMN "current_release_id";
ALTER TABLE "store_price_match_attempt" DROP COLUMN "suggested_release_id";
ALTER TABLE "store_price_match_attempt" DROP COLUMN "parent_bottle_id";
ALTER TABLE "store_price_match_attempt" DROP COLUMN "creation_target";
ALTER TABLE "store_price_match_proposal" DROP COLUMN "current_release_id";
ALTER TABLE "store_price_match_proposal" DROP COLUMN "suggested_release_id";
ALTER TABLE "store_price_match_proposal" DROP COLUMN "parent_bottle_id";
ALTER TABLE "store_price_match_proposal" DROP COLUMN "creation_target";
ALTER TABLE "store_price_match_proposal" DROP COLUMN "proposed_release";
ALTER TABLE "store_price" DROP COLUMN "release_id";
ALTER TABLE "tasting" DROP COLUMN "release_id";
DROP TYPE "public"."legacy_release_repair_review_resolution";
DROP TYPE "public"."store_price_match_creation_target";