-- Canonical vocabulary for flavors and aromas selected on tastings.
--
-- Canonical names are lowercase with normalized whitespace. Count nouns are
-- singular where natural; natural mass/collective terms remain unchanged.
-- Plurals, spelling variants, and interchangeable phrases live in synonyms.
-- Every descriptor maps to one existing whisky-wheel category. The separate
-- bottle flavor-profile taxonomy is intentionally not maintained here.
--
-- This Peated-authored vocabulary synthesizes:
-- https://doi.org/10.1002/j.2050-0416.2001.tb00099.x
-- https://www.whiskeymasters.org/whisky-tasting-wheel
-- https://www.agroscope.admin.ch/dam/agroscope/en/dokumente/themen/lebensmittel/sensorik/Whiskyrad_EN_klein.pdf.download.pdf/Whiskyrad_EN_klein.pdf
-- https://www.wsetglobal.com/knowledge-centre/wset-systematic-approach-to-tasting-sat/
-- https://doi.org/10.1111/1750-3841.14468
-- https://doi.org/10.1016/j.foodqual.2020.103926
-- and vocabulary sampled from public Peated tastings.
INSERT INTO "tag" ("name", "synonyms", "tag_category")
VALUES
  ('ale', ARRAY[]::varchar[], 'cereal'::"tag_category"),
  ('barley', ARRAY[]::varchar[], 'cereal'::"tag_category"),
  ('barley sugar', ARRAY[]::varchar[], 'cereal'::"tag_category"),
  ('biscuit', ARRAY['biscuity']::varchar[], 'cereal'::"tag_category"),
  ('bran', ARRAY[]::varchar[], 'cereal'::"tag_category"),
  ('bread', ARRAY[]::varchar[], 'cereal'::"tag_category"),
  ('brioche', ARRAY[]::varchar[], 'cereal'::"tag_category"),
  ('cake', ARRAY[]::varchar[], 'cereal'::"tag_category"),
  ('cereal', ARRAY[]::varchar[], 'cereal'::"tag_category"),
  ('corn', ARRAY[]::varchar[], 'cereal'::"tag_category"),
  ('cornbread', ARRAY['corn bread']::varchar[], 'cereal'::"tag_category"),
  ('cracker', ARRAY[]::varchar[], 'cereal'::"tag_category"),
  ('dough', ARRAY[]::varchar[], 'cereal'::"tag_category"),
  ('flour', ARRAY[]::varchar[], 'cereal'::"tag_category"),
  ('fresh hay', ARRAY[]::varchar[], 'cereal'::"tag_category"),
  ('grain', ARRAY['grains']::varchar[], 'cereal'::"tag_category"),
  ('granola', ARRAY[]::varchar[], 'cereal'::"tag_category"),
  ('hops', ARRAY['hop']::varchar[], 'cereal'::"tag_category"),
  ('malt', ARRAY[]::varchar[], 'cereal'::"tag_category"),
  ('malt extract', ARRAY[]::varchar[], 'cereal'::"tag_category"),
  ('malted barley', ARRAY[]::varchar[], 'cereal'::"tag_category"),
  ('malted milk', ARRAY[]::varchar[], 'cereal'::"tag_category"),
  ('mash', ARRAY['cooked mash']::varchar[], 'cereal'::"tag_category"),
  ('oat', ARRAY['oats']::varchar[], 'cereal'::"tag_category"),
  ('oatmeal', ARRAY[]::varchar[], 'cereal'::"tag_category"),
  ('pastry', ARRAY[]::varchar[], 'cereal'::"tag_category"),
  ('popcorn', ARRAY[]::varchar[], 'cereal'::"tag_category"),
  ('porridge', ARRAY[]::varchar[], 'cereal'::"tag_category"),
  ('potato skin', ARRAY['potato skins']::varchar[], 'cereal'::"tag_category"),
  ('rice pudding', ARRAY[]::varchar[], 'cereal'::"tag_category"),
  ('rye', ARRAY[]::varchar[], 'cereal'::"tag_category"),
  ('shortbread', ARRAY[]::varchar[], 'cereal'::"tag_category"),
  ('sourdough', ARRAY[]::varchar[], 'cereal'::"tag_category"),
  ('toast', ARRAY['toasted bread']::varchar[], 'cereal'::"tag_category"),
  ('wafer', ARRAY[]::varchar[], 'cereal'::"tag_category"),
  ('wheat', ARRAY[]::varchar[], 'cereal'::"tag_category"),
  ('yeast', ARRAY['yeasty']::varchar[], 'cereal'::"tag_category"),
  ('acidic', ARRAY[]::varchar[], 'fruity'::"tag_category"),
  ('apple', ARRAY['apples']::varchar[], 'fruity'::"tag_category"),
  ('apple pie', ARRAY[]::varchar[], 'fruity'::"tag_category"),
  ('apricot', ARRAY['apricots']::varchar[], 'fruity'::"tag_category"),
  ('baked apple', ARRAY['baked apples']::varchar[], 'fruity'::"tag_category"),
  ('banana', ARRAY['bananas']::varchar[], 'fruity'::"tag_category"),
  ('banana bread', ARRAY[]::varchar[], 'fruity'::"tag_category"),
  ('bergamot', ARRAY[]::varchar[], 'fruity'::"tag_category"),
  ('berry', ARRAY['berries']::varchar[], 'fruity'::"tag_category"),
  ('black cherry', ARRAY['dark cherry']::varchar[], 'fruity'::"tag_category"),
  ('blackberry', ARRAY['blackberries']::varchar[], 'fruity'::"tag_category"),
  ('blackcurrant', ARRAY['blackcurrants', 'black currant']::varchar[], 'fruity'::"tag_category"),
  ('blueberry', ARRAY['blueberries']::varchar[], 'fruity'::"tag_category"),
  ('bubble gum', ARRAY['bubblegum']::varchar[], 'fruity'::"tag_category"),
  ('candied fruit', ARRAY['candied fruits']::varchar[], 'fruity'::"tag_category"),
  ('cherry', ARRAY['cherries']::varchar[], 'fruity'::"tag_category"),
  ('cider', ARRAY['apple cider']::varchar[], 'fruity'::"tag_category"),
  ('citrus', ARRAY[]::varchar[], 'fruity'::"tag_category"),
  ('cranberry', ARRAY['cranberries']::varchar[], 'fruity'::"tag_category"),
  ('dark fruit', ARRAY['dark fruits', 'black fruit', 'black fruits']::varchar[], 'fruity'::"tag_category"),
  ('fruit', ARRAY['fruity']::varchar[], 'fruity'::"tag_category"),
  ('fruit candy', ARRAY[]::varchar[], 'fruity'::"tag_category"),
  ('fruit compote', ARRAY[]::varchar[], 'fruity'::"tag_category"),
  ('fruit salad', ARRAY[]::varchar[], 'fruity'::"tag_category"),
  ('gooseberry', ARRAY['gooseberries']::varchar[], 'fruity'::"tag_category"),
  ('grapefruit', ARRAY[]::varchar[], 'fruity'::"tag_category"),
  ('grape', ARRAY['grapes']::varchar[], 'fruity'::"tag_category"),
  ('green apple', ARRAY['granny smith', 'green apples']::varchar[], 'fruity'::"tag_category"),
  ('guava', ARRAY[]::varchar[], 'fruity'::"tag_category"),
  ('jam', ARRAY['jammy']::varchar[], 'fruity'::"tag_category"),
  ('kiwi', ARRAY['kiwifruit']::varchar[], 'fruity'::"tag_category"),
  ('lemon', ARRAY['lemons']::varchar[], 'fruity'::"tag_category"),
  ('lemon peel', ARRAY[]::varchar[], 'fruity'::"tag_category"),
  ('lemon zest', ARRAY[]::varchar[], 'fruity'::"tag_category"),
  ('lime', ARRAY['limes']::varchar[], 'fruity'::"tag_category"),
  ('lingonberry', ARRAY['lingonberries']::varchar[], 'fruity'::"tag_category"),
  ('lychee', ARRAY['litchi']::varchar[], 'fruity'::"tag_category"),
  ('mandarin', ARRAY[]::varchar[], 'fruity'::"tag_category"),
  ('mango', ARRAY['mangoes']::varchar[], 'fruity'::"tag_category"),
  ('marmalade', ARRAY[]::varchar[], 'fruity'::"tag_category"),
  ('melon', ARRAY[]::varchar[], 'fruity'::"tag_category"),
  ('mellow apricot', ARRAY[]::varchar[], 'fruity'::"tag_category"),
  ('nectarine', ARRAY['nectarines']::varchar[], 'fruity'::"tag_category"),
  ('orange', ARRAY['oranges']::varchar[], 'fruity'::"tag_category"),
  ('orange peel', ARRAY[]::varchar[], 'fruity'::"tag_category"),
  ('orchard fruit', ARRAY['orchard fruits']::varchar[], 'fruity'::"tag_category"),
  ('papaya', ARRAY[]::varchar[], 'fruity'::"tag_category"),
  ('passion fruit', ARRAY['passionfruit']::varchar[], 'fruity'::"tag_category"),
  ('peach', ARRAY['peaches']::varchar[], 'fruity'::"tag_category"),
  ('pear', ARRAY['pears']::varchar[], 'fruity'::"tag_category"),
  ('pear drop', ARRAY['pear drops']::varchar[], 'fruity'::"tag_category"),
  ('pineapple', ARRAY['pineapples']::varchar[], 'fruity'::"tag_category"),
  ('plum', ARRAY['plums']::varchar[], 'fruity'::"tag_category"),
  ('quince', ARRAY[]::varchar[], 'fruity'::"tag_category"),
  ('raspberry', ARRAY['raspberries']::varchar[], 'fruity'::"tag_category"),
  ('red apple', ARRAY['red apples']::varchar[], 'fruity'::"tag_category"),
  ('red fruit', ARRAY['red fruits']::varchar[], 'fruity'::"tag_category"),
  ('ripe apple', ARRAY['ripe apples']::varchar[], 'fruity'::"tag_category"),
  ('ripe melon', ARRAY[]::varchar[], 'fruity'::"tag_category"),
  ('ripe peach', ARRAY[]::varchar[], 'fruity'::"tag_category"),
  ('ripe pear', ARRAY['ripe pears']::varchar[], 'fruity'::"tag_category"),
  ('soft cherry', ARRAY[]::varchar[], 'fruity'::"tag_category"),
  ('solvent', ARRAY['acetone', 'nail polish remover']::varchar[], 'fruity'::"tag_category"),
  ('stone fruit', ARRAY['stonefruit']::varchar[], 'fruity'::"tag_category"),
  ('stewed fruit', ARRAY['stewed fruits']::varchar[], 'fruity'::"tag_category"),
  ('strawberry', ARRAY['strawberries']::varchar[], 'fruity'::"tag_category"),
  ('tangerine', ARRAY['tangerines']::varchar[], 'fruity'::"tag_category"),
  ('tropical fruit', ARRAY[]::varchar[], 'fruity'::"tag_category"),
  ('watermelon', ARRAY[]::varchar[], 'fruity'::"tag_category"),
  ('yuzu', ARRAY[]::varchar[], 'fruity'::"tag_category"),
  ('juicy pear', ARRAY['juicy pears']::varchar[], 'fruity'::"tag_category"),
  ('fresh berry', ARRAY['fresh berries']::varchar[], 'fruity'::"tag_category"),
  ('basil', ARRAY[]::varchar[], 'floral'::"tag_category"),
  ('chamomile', ARRAY[]::varchar[], 'floral'::"tag_category"),
  ('coriander', ARRAY['cilantro']::varchar[], 'floral'::"tag_category"),
  ('cut grass', ARRAY['fresh-cut grass', 'fresh cut grass']::varchar[], 'floral'::"tag_category"),
  ('delicate herb', ARRAY['delicate herbs']::varchar[], 'floral'::"tag_category"),
  ('dill', ARRAY[]::varchar[], 'floral'::"tag_category"),
  ('elderflower', ARRAY[]::varchar[], 'floral'::"tag_category"),
  ('eucalyptus', ARRAY[]::varchar[], 'floral'::"tag_category"),
  ('fern', ARRAY[]::varchar[], 'floral'::"tag_category"),
  ('fresh flower', ARRAY['fresh flowers']::varchar[], 'floral'::"tag_category"),
  ('flower', ARRAY['floral']::varchar[], 'floral'::"tag_category"),
  ('geranium', ARRAY['geraniums']::varchar[], 'floral'::"tag_category"),
  ('grass', ARRAY['grassy']::varchar[], 'floral'::"tag_category"),
  ('green herb', ARRAY['green herbs', 'herbal']::varchar[], 'floral'::"tag_category"),
  ('green leaf', ARRAY['green leaves', 'leafy']::varchar[], 'floral'::"tag_category"),
  ('green tea', ARRAY[]::varchar[], 'floral'::"tag_category"),
  ('green tomato', ARRAY['green tomatoes']::varchar[], 'floral'::"tag_category"),
  ('heather', ARRAY[]::varchar[], 'floral'::"tag_category"),
  ('honeysuckle', ARRAY[]::varchar[], 'floral'::"tag_category"),
  ('jasmine', ARRAY[]::varchar[], 'floral'::"tag_category"),
  ('lavender', ARRAY[]::varchar[], 'floral'::"tag_category"),
  ('lemongrass', ARRAY['lemon grass']::varchar[], 'floral'::"tag_category"),
  ('lilac', ARRAY[]::varchar[], 'floral'::"tag_category"),
  ('menthol', ARRAY[]::varchar[], 'floral'::"tag_category"),
  ('mint', ARRAY['minty']::varchar[], 'floral'::"tag_category"),
  ('orange blossom', ARRAY[]::varchar[], 'floral'::"tag_category"),
  ('pea pod', ARRAY['pea pods']::varchar[], 'floral'::"tag_category"),
  ('pine', ARRAY['pine needle', 'pine needles']::varchar[], 'floral'::"tag_category"),
  ('perfume', ARRAY['perfumed']::varchar[], 'floral'::"tag_category"),
  ('rosemary', ARRAY[]::varchar[], 'floral'::"tag_category"),
  ('rose', ARRAY['rose petal', 'rose petals']::varchar[], 'floral'::"tag_category"),
  ('sage', ARRAY[]::varchar[], 'floral'::"tag_category"),
  ('soft floral', ARRAY[]::varchar[], 'floral'::"tag_category"),
  ('tea', ARRAY[]::varchar[], 'floral'::"tag_category"),
  ('thyme', ARRAY[]::varchar[], 'floral'::"tag_category"),
  ('tobacco flower', ARRAY[]::varchar[], 'floral'::"tag_category"),
  ('violet', ARRAY['violets']::varchar[], 'floral'::"tag_category"),
  ('wildflower', ARRAY['wildflowers']::varchar[], 'floral'::"tag_category"),
  ('light floral', ARRAY[]::varchar[], 'floral'::"tag_category"),
  ('ash', ARRAY['ashy']::varchar[], 'peaty'::"tag_category"),
  ('bacon', ARRAY[]::varchar[], 'peaty'::"tag_category"),
  ('balanced smoke', ARRAY[]::varchar[], 'peaty'::"tag_category"),
  ('beach', ARRAY[]::varchar[], 'peaty'::"tag_category"),
  ('bonfire', ARRAY[]::varchar[], 'peaty'::"tag_category"),
  ('brine', ARRAY['briny']::varchar[], 'peaty'::"tag_category"),
  ('burnt rubber', ARRAY[]::varchar[], 'peaty'::"tag_category"),
  ('campfire', ARRAY[]::varchar[], 'peaty'::"tag_category"),
  ('char', ARRAY['charred']::varchar[], 'peaty'::"tag_category"),
  ('charcoal', ARRAY[]::varchar[], 'peaty'::"tag_category"),
  ('chalk', ARRAY['chalky']::varchar[], 'peaty'::"tag_category"),
  ('charred oak', ARRAY[]::varchar[], 'peaty'::"tag_category"),
  ('cigar smoke', ARRAY[]::varchar[], 'peaty'::"tag_category"),
  ('coal smoke', ARRAY[]::varchar[], 'peaty'::"tag_category"),
  ('creosote', ARRAY[]::varchar[], 'peaty'::"tag_category"),
  ('deep peat', ARRAY[]::varchar[], 'peaty'::"tag_category"),
  ('diesel', ARRAY['diesel oil']::varchar[], 'peaty'::"tag_category"),
  ('earthy peat', ARRAY[]::varchar[], 'peaty'::"tag_category"),
  ('ember', ARRAY['embers']::varchar[], 'peaty'::"tag_category"),
  ('fishing net', ARRAY['fishing nets']::varchar[], 'peaty'::"tag_category"),
  ('flint', ARRAY['flinty']::varchar[], 'peaty'::"tag_category"),
  ('gentle peat', ARRAY[]::varchar[], 'peaty'::"tag_category"),
  ('heavy iodine', ARRAY[]::varchar[], 'peaty'::"tag_category"),
  ('hemp rope', ARRAY[]::varchar[], 'peaty'::"tag_category"),
  ('incense', ARRAY[]::varchar[], 'peaty'::"tag_category"),
  ('intense smoke', ARRAY[]::varchar[], 'peaty'::"tag_category"),
  ('iodine', ARRAY[]::varchar[], 'peaty'::"tag_category"),
  ('light smoke', ARRAY[]::varchar[], 'peaty'::"tag_category"),
  ('medicinal', ARRAY['medicine']::varchar[], 'peaty'::"tag_category"),
  ('mineral', ARRAY['mineralic']::varchar[], 'peaty'::"tag_category"),
  ('moss', ARRAY['mossy']::varchar[], 'peaty'::"tag_category"),
  ('oyster', ARRAY['oysters']::varchar[], 'peaty'::"tag_category"),
  ('peat', ARRAY['peaty']::varchar[], 'peaty'::"tag_category"),
  ('peat moss', ARRAY[]::varchar[], 'peaty'::"tag_category"),
  ('salt', ARRAY['salty', 'sea salt']::varchar[], 'peaty'::"tag_category"),
  ('sea air', ARRAY['maritime air', 'salt spray', 'sea breeze', 'sea spray']::varchar[], 'peaty'::"tag_category"),
  ('seashell', ARRAY['seashells', 'sea shell', 'sea shells']::varchar[], 'peaty'::"tag_category"),
  ('seaweed', ARRAY['sea weed']::varchar[], 'peaty'::"tag_category"),
  ('shellfish', ARRAY[]::varchar[], 'peaty'::"tag_category"),
  ('smoke', ARRAY['smoky', 'smokey']::varchar[], 'peaty'::"tag_category"),
  ('smoked fish', ARRAY[]::varchar[], 'peaty'::"tag_category"),
  ('smoked herb', ARRAY['smoked herbs']::varchar[], 'peaty'::"tag_category"),
  ('smoked meat', ARRAY[]::varchar[], 'peaty'::"tag_category"),
  ('smoked salmon', ARRAY[]::varchar[], 'peaty'::"tag_category"),
  ('smoked wood', ARRAY[]::varchar[], 'peaty'::"tag_category"),
  ('soot', ARRAY['sooty']::varchar[], 'peaty'::"tag_category"),
  ('sour ash', ARRAY[]::varchar[], 'peaty'::"tag_category"),
  ('tar', ARRAY['tarry']::varchar[], 'peaty'::"tag_category"),
  ('turf', ARRAY[]::varchar[], 'peaty'::"tag_category"),
  ('wet earth', ARRAY[]::varchar[], 'peaty'::"tag_category"),
  ('wet stone', ARRAY['wet stones']::varchar[], 'peaty'::"tag_category"),
  ('wood smoke', ARRAY[]::varchar[], 'peaty'::"tag_category"),
  ('alcohol burn', ARRAY[]::varchar[], 'peaty'::"tag_category"),
  ('autumn leaf', ARRAY['autumn leaves']::varchar[], 'feinty'::"tag_category"),
  ('antique leather', ARRAY[]::varchar[], 'feinty'::"tag_category"),
  ('beeswax', ARRAY['bee''s wax']::varchar[], 'feinty'::"tag_category"),
  ('broth', ARRAY[]::varchar[], 'feinty'::"tag_category"),
  ('buttermilk', ARRAY[]::varchar[], 'feinty'::"tag_category"),
  ('cheese', ARRAY['cheesy']::varchar[], 'feinty'::"tag_category"),
  ('clover honey', ARRAY[]::varchar[], 'feinty'::"tag_category"),
  ('damp earth', ARRAY[]::varchar[], 'feinty'::"tag_category"),
  ('earthiness', ARRAY['earthy']::varchar[], 'feinty'::"tag_category"),
  ('farmyard', ARRAY['barnyard']::varchar[], 'feinty'::"tag_category"),
  ('forest floor', ARRAY[]::varchar[], 'feinty'::"tag_category"),
  ('funk', ARRAY['funky']::varchar[], 'feinty'::"tag_category"),
  ('heather honey', ARRAY[]::varchar[], 'feinty'::"tag_category"),
  ('honey', ARRAY['honeyed']::varchar[], 'feinty'::"tag_category"),
  ('honeycomb', ARRAY['honey comb']::varchar[], 'feinty'::"tag_category"),
  ('leather', ARRAY['leathery']::varchar[], 'feinty'::"tag_category"),
  ('library book', ARRAY['library books']::varchar[], 'feinty'::"tag_category"),
  ('mead', ARRAY[]::varchar[], 'feinty'::"tag_category"),
  ('meat', ARRAY['meaty']::varchar[], 'feinty'::"tag_category"),
  ('mushroom', ARRAY['mushrooms']::varchar[], 'feinty'::"tag_category"),
  ('must', ARRAY['musty']::varchar[], 'feinty'::"tag_category"),
  ('old book', ARRAY['old books']::varchar[], 'feinty'::"tag_category"),
  ('polish', ARRAY[]::varchar[], 'feinty'::"tag_category"),
  ('shoe polish', ARRAY[]::varchar[], 'feinty'::"tag_category"),
  ('soft musk', ARRAY[]::varchar[], 'feinty'::"tag_category"),
  ('sweat', ARRAY['sweaty']::varchar[], 'feinty'::"tag_category"),
  ('tobacco', ARRAY[]::varchar[], 'feinty'::"tag_category"),
  ('tobacco ash', ARRAY[]::varchar[], 'feinty'::"tag_category"),
  ('tobacco leaf', ARRAY[]::varchar[], 'feinty'::"tag_category"),
  ('umami', ARRAY['savory', 'savoury']::varchar[], 'feinty'::"tag_category"),
  ('wax', ARRAY['waxy']::varchar[], 'feinty'::"tag_category"),
  ('wet wool', ARRAY[]::varchar[], 'feinty'::"tag_category"),
  ('burnt match', ARRAY['burnt matches']::varchar[], 'sulphury'::"tag_category"),
  ('cabbage', ARRAY[]::varchar[], 'sulphury'::"tag_category"),
  ('cabbage water', ARRAY[]::varchar[], 'sulphury'::"tag_category"),
  ('copper', ARRAY[]::varchar[], 'sulphury'::"tag_category"),
  ('electric cable', ARRAY['electric cables']::varchar[], 'sulphury'::"tag_category"),
  ('firework', ARRAY['fireworks', 'spent firework']::varchar[], 'sulphury'::"tag_category"),
  ('garlic', ARRAY[]::varchar[], 'sulphury'::"tag_category"),
  ('gunpowder', ARRAY[]::varchar[], 'sulphury'::"tag_category"),
  ('marsh gas', ARRAY[]::varchar[], 'sulphury'::"tag_category"),
  ('matchbox', ARRAY[]::varchar[], 'sulphury'::"tag_category"),
  ('metal', ARRAY['metallic']::varchar[], 'sulphury'::"tag_category"),
  ('new tire', ARRAY['new tires', 'new tyre', 'new tyres']::varchar[], 'sulphury'::"tag_category"),
  ('onion', ARRAY['onions']::varchar[], 'sulphury'::"tag_category"),
  ('pencil eraser', ARRAY[]::varchar[], 'sulphury'::"tag_category"),
  ('rotten egg', ARRAY['rotten eggs']::varchar[], 'sulphury'::"tag_category"),
  ('rubber', ARRAY['rubbery']::varchar[], 'sulphury'::"tag_category"),
  ('stagnant water', ARRAY[]::varchar[], 'sulphury'::"tag_category"),
  ('starch', ARRAY['starchy']::varchar[], 'sulphury'::"tag_category"),
  ('struck match', ARRAY['struck matches']::varchar[], 'sulphury'::"tag_category"),
  ('sulfur', ARRAY['sulphur', 'sulfurous', 'sulphurous']::varchar[], 'sulphury'::"tag_category"),
  ('turnip', ARRAY['turnips']::varchar[], 'sulphury'::"tag_category"),
  ('allspice', ARRAY[]::varchar[], 'woody'::"tag_category"),
  ('anise', ARRAY['aniseed']::varchar[], 'woody'::"tag_category"),
  ('antique wood', ARRAY[]::varchar[], 'woody'::"tag_category"),
  ('baking spices', ARRAY['baking spice']::varchar[], 'woody'::"tag_category"),
  ('black pepper', ARRAY['pepper', 'peppercorn']::varchar[], 'woody'::"tag_category"),
  ('brown sugar', ARRAY[]::varchar[], 'woody'::"tag_category"),
  ('brown butter', ARRAY[]::varchar[], 'woody'::"tag_category"),
  ('burnt sugar', ARRAY[]::varchar[], 'woody'::"tag_category"),
  ('butter', ARRAY['buttery']::varchar[], 'woody'::"tag_category"),
  ('butterscotch', ARRAY[]::varchar[], 'woody'::"tag_category"),
  ('caramel', ARRAY['caramelized sugar', 'caramelised sugar']::varchar[], 'woody'::"tag_category"),
  ('cardamom', ARRAY[]::varchar[], 'woody'::"tag_category"),
  ('cedar', ARRAY['cedarwood']::varchar[], 'woody'::"tag_category"),
  ('cinnamon', ARRAY[]::varchar[], 'woody'::"tag_category"),
  ('cigar box', ARRAY[]::varchar[], 'woody'::"tag_category"),
  ('clove', ARRAY['cloves']::varchar[], 'woody'::"tag_category"),
  ('cola', ARRAY[]::varchar[], 'woody'::"tag_category"),
  ('coconut', ARRAY['toasted coconut']::varchar[], 'woody'::"tag_category"),
  ('creamy oak', ARRAY[]::varchar[], 'woody'::"tag_category"),
  ('custard', ARRAY[]::varchar[], 'woody'::"tag_category"),
  ('fennel', ARRAY[]::varchar[], 'woody'::"tag_category"),
  ('ginger', ARRAY[]::varchar[], 'woody'::"tag_category"),
  ('gingerbread', ARRAY[]::varchar[], 'woody'::"tag_category"),
  ('licorice', ARRAY['liquorice']::varchar[], 'woody'::"tag_category"),
  ('maple', ARRAY[]::varchar[], 'woody'::"tag_category"),
  ('maple syrup', ARRAY[]::varchar[], 'woody'::"tag_category"),
  ('molasses', ARRAY[]::varchar[], 'woody'::"tag_category"),
  ('marshmallow', ARRAY['marshmallows']::varchar[], 'woody'::"tag_category"),
  ('new oak', ARRAY[]::varchar[], 'woody'::"tag_category"),
  ('nutmeg', ARRAY[]::varchar[], 'woody'::"tag_category"),
  ('oak', ARRAY['oaky']::varchar[], 'woody'::"tag_category"),
  ('oak spice', ARRAY['oak spices']::varchar[], 'woody'::"tag_category"),
  ('old oak', ARRAY[]::varchar[], 'woody'::"tag_category"),
  ('old wood', ARRAY[]::varchar[], 'woody'::"tag_category"),
  ('pencil shaving', ARRAY['pencil shavings']::varchar[], 'woody'::"tag_category"),
  ('polished wood', ARRAY[]::varchar[], 'woody'::"tag_category"),
  ('red pepper', ARRAY[]::varchar[], 'woody'::"tag_category"),
  ('resin', ARRAY['resinous']::varchar[], 'woody'::"tag_category"),
  ('root beer', ARRAY['rootbeer']::varchar[], 'woody'::"tag_category"),
  ('sandalwood', ARRAY[]::varchar[], 'woody'::"tag_category"),
  ('spice', ARRAY['spicy']::varchar[], 'woody'::"tag_category"),
  ('toffee', ARRAY[]::varchar[], 'woody'::"tag_category"),
  ('toasted oak', ARRAY[]::varchar[], 'woody'::"tag_category"),
  ('treacle', ARRAY[]::varchar[], 'woody'::"tag_category"),
  ('vanilla', ARRAY[]::varchar[], 'woody'::"tag_category"),
  ('vanilla bean', ARRAY[]::varchar[], 'woody'::"tag_category"),
  ('white pepper', ARRAY[]::varchar[], 'woody'::"tag_category"),
  ('wood', ARRAY['woody']::varchar[], 'woody'::"tag_category"),
  ('almond', ARRAY['almonds']::varchar[], 'winey'::"tag_category"),
  ('aged sherry', ARRAY[]::varchar[], 'winey'::"tag_category"),
  ('amontillado', ARRAY[]::varchar[], 'winey'::"tag_category"),
  ('armagnac', ARRAY[]::varchar[], 'winey'::"tag_category"),
  ('cacao', ARRAY[]::varchar[], 'winey'::"tag_category"),
  ('cabernet', ARRAY['cabernet sauvignon']::varchar[], 'winey'::"tag_category"),
  ('candle wax', ARRAY['candlewax']::varchar[], 'winey'::"tag_category"),
  ('chardonnay', ARRAY[]::varchar[], 'winey'::"tag_category"),
  ('chocolate', ARRAY[]::varchar[], 'winey'::"tag_category"),
  ('cocoa', ARRAY[]::varchar[], 'winey'::"tag_category"),
  ('coffee', ARRAY[]::varchar[], 'winey'::"tag_category"),
  ('coffee bean', ARRAY['coffee beans']::varchar[], 'winey'::"tag_category"),
  ('cognac', ARRAY[]::varchar[], 'winey'::"tag_category"),
  ('cream', ARRAY['creamy']::varchar[], 'winey'::"tag_category"),
  ('currant', ARRAY['currants']::varchar[], 'winey'::"tag_category"),
  ('dark chocolate', ARRAY[]::varchar[], 'winey'::"tag_category"),
  ('date', ARRAY['dates']::varchar[], 'winey'::"tag_category"),
  ('dried apricot', ARRAY['dried apricots']::varchar[], 'winey'::"tag_category"),
  ('dried cherry', ARRAY['dried cherries']::varchar[], 'winey'::"tag_category"),
  ('dried fig', ARRAY['dried figs']::varchar[], 'winey'::"tag_category"),
  ('dried fruit', ARRAY['dried fruits']::varchar[], 'winey'::"tag_category"),
  ('espresso', ARRAY[]::varchar[], 'winey'::"tag_category"),
  ('fig', ARRAY['figs']::varchar[], 'winey'::"tag_category"),
  ('fino', ARRAY['fino sherry']::varchar[], 'winey'::"tag_category"),
  ('fruitcake', ARRAY['fruit cake']::varchar[], 'winey'::"tag_category"),
  ('hazelnut', ARRAY['hazelnuts']::varchar[], 'winey'::"tag_category"),
  ('linseed oil', ARRAY[]::varchar[], 'winey'::"tag_category"),
  ('luxurious sherry', ARRAY[]::varchar[], 'winey'::"tag_category"),
  ('madeira', ARRAY[]::varchar[], 'winey'::"tag_category"),
  ('marzipan', ARRAY[]::varchar[], 'winey'::"tag_category"),
  ('milk chocolate', ARRAY[]::varchar[], 'winey'::"tag_category"),
  ('mocha', ARRAY[]::varchar[], 'winey'::"tag_category"),
  ('nut', ARRAY['nuts', 'nutty']::varchar[], 'winey'::"tag_category"),
  ('oil', ARRAY['oily']::varchar[], 'winey'::"tag_category"),
  ('olive oil', ARRAY[]::varchar[], 'winey'::"tag_category"),
  ('oloroso', ARRAY['oloroso sherry']::varchar[], 'winey'::"tag_category"),
  ('pecan', ARRAY['pecans']::varchar[], 'winey'::"tag_category"),
  ('peanut', ARRAY['peanuts']::varchar[], 'winey'::"tag_category"),
  ('port', ARRAY['port wine']::varchar[], 'winey'::"tag_category"),
  ('praline', ARRAY[]::varchar[], 'winey'::"tag_category"),
  ('prune', ARRAY['prunes']::varchar[], 'winey'::"tag_category"),
  ('raisin', ARRAY['raisins']::varchar[], 'winey'::"tag_category"),
  ('red wine', ARRAY[]::varchar[], 'winey'::"tag_category"),
  ('rich prune', ARRAY['rich prunes']::varchar[], 'winey'::"tag_category"),
  ('roasted coffee', ARRAY[]::varchar[], 'winey'::"tag_category"),
  ('rum', ARRAY[]::varchar[], 'winey'::"tag_category"),
  ('sauternes', ARRAY[]::varchar[], 'winey'::"tag_category"),
  ('sherry', ARRAY[]::varchar[], 'winey'::"tag_category"),
  ('sultana', ARRAY['sultanas']::varchar[], 'winey'::"tag_category"),
  ('toasted almond', ARRAY['toasted almonds']::varchar[], 'winey'::"tag_category"),
  ('walnut', ARRAY['walnuts']::varchar[], 'winey'::"tag_category"),
  ('white wine', ARRAY[]::varchar[], 'winey'::"tag_category")
ON CONFLICT ("name") DO UPDATE SET
  "synonyms" = EXCLUDED."synonyms",
  "tag_category" = EXCLUDED."tag_category";
--> statement-breakpoint
-- These 21 names were verified as production tag rows on 2026-08-02. Most are
-- plural/style normalization; juicy pear/juicy pears is the coexisting pair.
WITH "replacement"("old_name", "new_name") AS (
  VALUES
    ('biscuity'::varchar, 'biscuit'::varchar),
    ('grains'::varchar, 'grain'::varchar),
    ('ripe apples'::varchar, 'ripe apple'::varchar),
    ('stewed fruits'::varchar, 'stewed fruit'::varchar),
    ('juicy pears'::varchar, 'juicy pear'::varchar),
    ('fresh berries'::varchar, 'fresh berry'::varchar),
    ('delicate herbs'::varchar, 'delicate herb'::varchar),
    ('fresh flowers'::varchar, 'fresh flower'::varchar),
    ('green leaves'::varchar, 'green leaf'::varchar),
    ('smoked herbs'::varchar, 'smoked herb'::varchar),
    ('library books'::varchar, 'library book'::varchar),
    ('old books'::varchar, 'old book'::varchar),
    ('burnt matches'::varchar, 'burnt match'::varchar),
    ('oak spices'::varchar, 'oak spice'::varchar),
    ('coffee beans'::varchar, 'coffee bean'::varchar),
    ('currants'::varchar, 'currant'::varchar),
    ('dried figs'::varchar, 'dried fig'::varchar),
    ('fruit cake'::varchar, 'fruitcake'::varchar),
    ('raisins'::varchar, 'raisin'::varchar),
    ('rich prunes'::varchar, 'rich prune'::varchar),
    ('toasted almonds'::varchar, 'toasted almond'::varchar)
),
"normalized" AS (
  SELECT
    "tasting"."id",
    ARRAY(
      SELECT "deduplicated"."value"
      FROM (
        SELECT
          COALESCE("replacement"."new_name", "source"."value") AS "value",
          MIN("source"."position") AS "first_position"
        FROM unnest("tasting"."tags") WITH ORDINALITY AS "source"("value", "position")
        LEFT JOIN "replacement"
          ON "replacement"."old_name" = "source"."value"
        GROUP BY COALESCE("replacement"."new_name", "source"."value")
      ) AS "deduplicated"
      ORDER BY "deduplicated"."first_position"
    )::varchar[] AS "tags"
  FROM "tasting"
  WHERE "tasting"."tags" && ARRAY(
    SELECT "replacement"."old_name" FROM "replacement"
  )::varchar[]
)
UPDATE "tasting"
SET "tags" = "normalized"."tags"
FROM "normalized"
WHERE "tasting"."id" = "normalized"."id";
--> statement-breakpoint
WITH "replacement"("old_name", "new_name") AS (
  VALUES
    ('biscuity'::varchar, 'biscuit'::varchar),
    ('grains'::varchar, 'grain'::varchar),
    ('ripe apples'::varchar, 'ripe apple'::varchar),
    ('stewed fruits'::varchar, 'stewed fruit'::varchar),
    ('juicy pears'::varchar, 'juicy pear'::varchar),
    ('fresh berries'::varchar, 'fresh berry'::varchar),
    ('delicate herbs'::varchar, 'delicate herb'::varchar),
    ('fresh flowers'::varchar, 'fresh flower'::varchar),
    ('green leaves'::varchar, 'green leaf'::varchar),
    ('smoked herbs'::varchar, 'smoked herb'::varchar),
    ('library books'::varchar, 'library book'::varchar),
    ('old books'::varchar, 'old book'::varchar),
    ('burnt matches'::varchar, 'burnt match'::varchar),
    ('oak spices'::varchar, 'oak spice'::varchar),
    ('coffee beans'::varchar, 'coffee bean'::varchar),
    ('currants'::varchar, 'currant'::varchar),
    ('dried figs'::varchar, 'dried fig'::varchar),
    ('fruit cake'::varchar, 'fruitcake'::varchar),
    ('raisins'::varchar, 'raisin'::varchar),
    ('rich prunes'::varchar, 'rich prune'::varchar),
    ('toasted almonds'::varchar, 'toasted almond'::varchar)
),
"normalized" AS (
  SELECT
    "bottle"."id",
    ARRAY(
      SELECT "deduplicated"."value"
      FROM (
        SELECT
          COALESCE("replacement"."new_name", "source"."value") AS "value",
          MIN("source"."position") AS "first_position"
        FROM unnest("bottle"."suggested_tags") WITH ORDINALITY AS "source"("value", "position")
        LEFT JOIN "replacement"
          ON "replacement"."old_name" = "source"."value"
        GROUP BY COALESCE("replacement"."new_name", "source"."value")
      ) AS "deduplicated"
      ORDER BY "deduplicated"."first_position"
    )::varchar[] AS "suggested_tags"
  FROM "bottle"
  WHERE "bottle"."suggested_tags" && ARRAY(
    SELECT "replacement"."old_name" FROM "replacement"
  )::varchar[]
)
UPDATE "bottle"
SET "suggested_tags" = "normalized"."suggested_tags"
FROM "normalized"
WHERE "bottle"."id" = "normalized"."id";
--> statement-breakpoint
WITH "replacement"("old_name", "new_name") AS (
  VALUES
    ('biscuity'::varchar, 'biscuit'::varchar),
    ('grains'::varchar, 'grain'::varchar),
    ('ripe apples'::varchar, 'ripe apple'::varchar),
    ('stewed fruits'::varchar, 'stewed fruit'::varchar),
    ('juicy pears'::varchar, 'juicy pear'::varchar),
    ('fresh berries'::varchar, 'fresh berry'::varchar),
    ('delicate herbs'::varchar, 'delicate herb'::varchar),
    ('fresh flowers'::varchar, 'fresh flower'::varchar),
    ('green leaves'::varchar, 'green leaf'::varchar),
    ('smoked herbs'::varchar, 'smoked herb'::varchar),
    ('library books'::varchar, 'library book'::varchar),
    ('old books'::varchar, 'old book'::varchar),
    ('burnt matches'::varchar, 'burnt match'::varchar),
    ('oak spices'::varchar, 'oak spice'::varchar),
    ('coffee beans'::varchar, 'coffee bean'::varchar),
    ('currants'::varchar, 'currant'::varchar),
    ('dried figs'::varchar, 'dried fig'::varchar),
    ('fruit cake'::varchar, 'fruitcake'::varchar),
    ('raisins'::varchar, 'raisin'::varchar),
    ('rich prunes'::varchar, 'rich prune'::varchar),
    ('toasted almonds'::varchar, 'toasted almond'::varchar)
),
"affected_tag"("name") AS (
  SELECT "old_name" FROM "replacement"
  UNION
  SELECT "new_name" FROM "replacement"
)
DELETE FROM "bottle_tag"
USING "affected_tag"
WHERE "bottle_tag"."tag" = "affected_tag"."name";
--> statement-breakpoint
WITH "replacement"("old_name", "new_name") AS (
  VALUES
    ('biscuity'::varchar, 'biscuit'::varchar),
    ('grains'::varchar, 'grain'::varchar),
    ('ripe apples'::varchar, 'ripe apple'::varchar),
    ('stewed fruits'::varchar, 'stewed fruit'::varchar),
    ('juicy pears'::varchar, 'juicy pear'::varchar),
    ('fresh berries'::varchar, 'fresh berry'::varchar),
    ('delicate herbs'::varchar, 'delicate herb'::varchar),
    ('fresh flowers'::varchar, 'fresh flower'::varchar),
    ('green leaves'::varchar, 'green leaf'::varchar),
    ('smoked herbs'::varchar, 'smoked herb'::varchar),
    ('library books'::varchar, 'library book'::varchar),
    ('old books'::varchar, 'old book'::varchar),
    ('burnt matches'::varchar, 'burnt match'::varchar),
    ('oak spices'::varchar, 'oak spice'::varchar),
    ('coffee beans'::varchar, 'coffee bean'::varchar),
    ('currants'::varchar, 'currant'::varchar),
    ('dried figs'::varchar, 'dried fig'::varchar),
    ('fruit cake'::varchar, 'fruitcake'::varchar),
    ('raisins'::varchar, 'raisin'::varchar),
    ('rich prunes'::varchar, 'rich prune'::varchar),
    ('toasted almonds'::varchar, 'toasted almond'::varchar)
)
INSERT INTO "bottle_tag" ("bottle_id", "tag", "count")
SELECT
  "tasting"."bottle_id",
  "selected_tag"."name",
  COUNT(*)::integer
FROM "tasting"
CROSS JOIN LATERAL unnest("tasting"."tags") AS "selected_tag"("name")
WHERE "selected_tag"."name" IN (
  SELECT "replacement"."new_name" FROM "replacement"
)
GROUP BY "tasting"."bottle_id", "selected_tag"."name"
ON CONFLICT ("bottle_id", "tag") DO UPDATE SET
  "count" = EXCLUDED."count";
--> statement-breakpoint
WITH "replacement"("old_name", "new_name") AS (
  VALUES
    ('biscuity'::varchar, 'biscuit'::varchar),
    ('grains'::varchar, 'grain'::varchar),
    ('ripe apples'::varchar, 'ripe apple'::varchar),
    ('stewed fruits'::varchar, 'stewed fruit'::varchar),
    ('juicy pears'::varchar, 'juicy pear'::varchar),
    ('fresh berries'::varchar, 'fresh berry'::varchar),
    ('delicate herbs'::varchar, 'delicate herb'::varchar),
    ('fresh flowers'::varchar, 'fresh flower'::varchar),
    ('green leaves'::varchar, 'green leaf'::varchar),
    ('smoked herbs'::varchar, 'smoked herb'::varchar),
    ('library books'::varchar, 'library book'::varchar),
    ('old books'::varchar, 'old book'::varchar),
    ('burnt matches'::varchar, 'burnt match'::varchar),
    ('oak spices'::varchar, 'oak spice'::varchar),
    ('coffee beans'::varchar, 'coffee bean'::varchar),
    ('currants'::varchar, 'currant'::varchar),
    ('dried figs'::varchar, 'dried fig'::varchar),
    ('fruit cake'::varchar, 'fruitcake'::varchar),
    ('raisins'::varchar, 'raisin'::varchar),
    ('rich prunes'::varchar, 'rich prune'::varchar),
    ('toasted almonds'::varchar, 'toasted almond'::varchar)
)
DELETE FROM "tag"
USING "replacement"
WHERE "tag"."name" = "replacement"."old_name";
