import registry from "../registry";
import capturePriceImage from "./capturePriceImage";
import createMissingBottles from "./createMissingBottles";
import generateBottleDetails from "./generateBottleDetails";
import generateCountryDetails from "./generateCountryDetails";
import generateEntityDetails from "./generateEntityDetails";
import generateRegionDetails from "./generateRegionDetails";
import geocodeCountryLocation from "./geocodeCountryLocation";
import geocodeEntityLocation from "./geocodeEntityLocation";
import geocodeRegionLocation from "./geocodeRegionLocation";
import indexBottleAlias from "./indexBottleAlias";
import indexBottleReleaseSearchVectors from "./indexBottleReleaseSearchVectors";
import indexBottleSearchVectors from "./indexBottleSearchVectors";
import indexBottleSeriesSearchVectors from "./indexBottleSeriesSearchVectors";
import indexEntitySearchVectors from "./indexEntitySearchVectors";
import mergeBottle from "./mergeBottle";
import mergeEntity from "./mergeEntity";
import notifyDiscordOnTasting from "./notifyDiscordOnTasting";
import onBottleAliasChange from "./onBottleAliasChange";
import onBottleChange from "./onBottleChange";
import onBottleReleaseChange from "./onBottleReleaseChange";
import onEntityChange from "./onEntityChange";
import processNotification from "./processNotification";
import scrapeAstorWines from "./scrapeAstorWines";
import scrapeHealthySpirits from "./scrapeHealthySpirits";
import scrapeReserveBar from "./scrapeReserveBar";
import scrapeSMWS from "./scrapeSMWS";
import scrapeSMWSA from "./scrapeSMWSA";
import scrapeTotalWine from "./scrapeTotalWine";
import scrapeWhiskeyAdvocate from "./scrapeWhiskyAdvocate";
import scrapeWoodenCork from "./scrapeWoodenCork";
import updateBottleStats from "./updateBottleStats";
import updateCountryStats from "./updateCountryStats";
import updateEntityStats from "./updateEntityStats";
import updateRegionStats from "./updateRegionStats";

registry.add("CapturePriceImage", capturePriceImage);
registry.add("GenerateBottleDetails", generateBottleDetails);
registry.add("GenerateCountryDetails", generateCountryDetails);
registry.add("GenerateEntityDetails", generateEntityDetails);
registry.add("GenerateRegionDetails", generateRegionDetails);
registry.add("GeocodeCountryLocation", geocodeCountryLocation);
registry.add("GeocodeRegionLocation", geocodeRegionLocation);
registry.add("GeocodeEntityLocation", geocodeEntityLocation);
registry.add("IndexBottleAlias", indexBottleAlias);
registry.add("IndexBottleSearchVectors", indexBottleSearchVectors);
registry.add(
  "IndexBottleReleaseSearchVectors",
  indexBottleReleaseSearchVectors
);
registry.add("IndexBottleSeriesSearchVectors", indexBottleSeriesSearchVectors);
registry.add("IndexEntitySearchVectors", indexEntitySearchVectors);
registry.add("MergeBottle", mergeBottle);
registry.add("MergeEntity", mergeEntity);
registry.add("NotifyDiscordOnTasting", notifyDiscordOnTasting);
registry.add("OnBottleAliasChange", onBottleAliasChange);
registry.add("OnBottleChange", onBottleChange);
registry.add("OnBottleReleaseChange", onBottleReleaseChange);
registry.add("OnEntityChange", onEntityChange);
registry.add("ProcessNotification", processNotification);
registry.add("ScrapeAstorWines", scrapeAstorWines);
registry.add("ScrapeHealthySpirits", scrapeHealthySpirits);
registry.add("ScrapeReserveBar", scrapeReserveBar);
registry.add("ScrapeSMWS", scrapeSMWS);
registry.add("ScrapeSMWSA", scrapeSMWSA);
registry.add("ScrapeTotalWine", scrapeTotalWine);
registry.add("ScrapeWoodenCork", scrapeWoodenCork);
registry.add("ScrapeWhiskyAdvocate", scrapeWhiskeyAdvocate);
registry.add("CreateMissingBottles", createMissingBottles);
registry.add("UpdateBottleStats", updateBottleStats);
registry.add("UpdateCountryStats", updateCountryStats);
registry.add("UpdateEntityStats", updateEntityStats);
registry.add("UpdateRegionStats", updateRegionStats);
