import registry from "../registry";
import capturePriceImage from "./capturePriceImage";
import cleanupPendingUploads from "./cleanupPendingUploads";
import createMissingBottles from "./createMissingBottles";
import generateBottleDetails from "./generateBottleDetails";
import generateCountryDetails from "./generateCountryDetails";
import generateEntityDetails from "./generateEntityDetails";
import generateRegionDetails from "./generateRegionDetails";
import geocodeCountryLocation from "./geocodeCountryLocation";
import geocodeEntityLocation from "./geocodeEntityLocation";
import geocodeRegionLocation from "./geocodeRegionLocation";
import indexBottleAlias from "./indexBottleAlias";
import indexBottleSearchVectors from "./indexBottleSearchVectors";
import indexBottleSeriesSearchVectors from "./indexBottleSeriesSearchVectors";
import indexEntitySearchVectors from "./indexEntitySearchVectors";
import mergeEntity from "./mergeEntity";
import notifyDiscordOnTasting from "./notifyDiscordOnTasting";
import onBottleAliasChange from "./onBottleAliasChange";
import onBottleChange from "./onBottleChange";
import onEntityChange from "./onEntityChange";
import processNotification from "./processNotification";
import processStorePriceMatchRetryRun from "./processStorePriceMatchRetryRun";
import reconcileStorePriceMatchProposals from "./reconcileStorePriceMatchProposals";
import resolveStorePriceBottle from "./resolveStorePriceBottle";
import runScraper from "./runScraper";
import updateBottleStats from "./updateBottleStats";
import updateCountryStats from "./updateCountryStats";
import updateEntityStats from "./updateEntityStats";
import updateRegionStats from "./updateRegionStats";
import verifyBottleCreation from "./verifyBottleCreation";
import verifyEntityCreation from "./verifyEntityCreation";

registry.add("CapturePriceImage", capturePriceImage);
registry.add("CleanupPendingUploads", cleanupPendingUploads);
registry.add("GenerateBottleDetails", generateBottleDetails);
registry.add("GenerateCountryDetails", generateCountryDetails);
registry.add("GenerateEntityDetails", generateEntityDetails);
registry.add("GenerateRegionDetails", generateRegionDetails);
registry.add("GeocodeCountryLocation", geocodeCountryLocation);
registry.add("GeocodeRegionLocation", geocodeRegionLocation);
registry.add("GeocodeEntityLocation", geocodeEntityLocation);
registry.add("IndexBottleAlias", indexBottleAlias);
registry.add("IndexBottleSearchVectors", indexBottleSearchVectors);
registry.add("IndexBottleSeriesSearchVectors", indexBottleSeriesSearchVectors);
registry.add("IndexEntitySearchVectors", indexEntitySearchVectors);
registry.add("MergeEntity", mergeEntity);
registry.add("NotifyDiscordOnTasting", notifyDiscordOnTasting);
registry.add("OnBottleAliasChange", onBottleAliasChange);
registry.add("OnBottleChange", onBottleChange);
registry.add("OnEntityChange", onEntityChange);
registry.add("ProcessNotification", processNotification);
registry.add("ProcessStorePriceMatchRetryRun", processStorePriceMatchRetryRun);
registry.add(
  "ReconcileStorePriceMatchProposals",
  reconcileStorePriceMatchProposals,
);
registry.add("ResolveStorePriceBottle", resolveStorePriceBottle);
registry.add("RunScraper", runScraper, { queueName: "scrapers" });
registry.add("CreateMissingBottles", createMissingBottles);
registry.add("UpdateBottleStats", updateBottleStats);
registry.add("UpdateCountryStats", updateCountryStats);
registry.add("UpdateEntityStats", updateEntityStats);
registry.add("UpdateRegionStats", updateRegionStats);
registry.add("VerifyBottleCreation", verifyBottleCreation);
registry.add("VerifyEntityCreation", verifyEntityCreation);
