name: GCP Deploy
on:
  # push:
  #   branches:
  #     - main
  # TODO: dont ship w/ this!
  pull_request:
jobs:
  build:
    name: 🚀 Build
    runs-on: ubuntu-latest
    permissions:
      contents: "read"
      id-token: "write"
    env:
      GAR_LOCATION: us-central1
      PROJECT_ID: cask-382601
      SENTRY_DSN:
      GOOGLE_CLIENT_ID:
      API_SERVER: https://api.peated.app
    steps:
      - name: 🛑 Cancel Previous Runs
        uses: styfle/cancel-workflow-action@0.11.0

      - name: ⬇️ Checkout repo
        uses: actions/checkout@v3

      - name: "Google auth"
        id: "auth"
        uses: "google-github-actions/auth@v1"
        with:
          token_format: access_token
          workload_identity_provider: ${{ secrets.WORKLOAD_IDENTITY_PROVIDER_RESOURCE_NAME }}
          service_account: ${{ secrets.SERVICE_ACCOUNT }}@${{ env.PROJECT_ID }}.iam.gserviceaccount.com
          access_token_lifetime: 300s
      # - name: Login to Artifact Registry
      #   uses: docker/login-action@v1
      #   with:
      #     registry: us-central-docker.pkg.dev
      #     username: oauth2accesstoken
      #     password: ${{ steps.auth.outputs.access_token }}
      - name: "Set up Cloud SDK"
        uses: "google-github-actions/setup-gcloud@v1"
        with:
          project_id: "${{ env.PROJECT_ID }}"

      - name: "Docker auth"
        run: |-
          gcloud auth configure-docker ${{ env.GAR_LOCATION }}-docker.pkg.dev

      - name: Record Version
        id: vars
        run: echo "sha_short=$(git rev-parse --short HEAD)" >> $GITHUB_OUTPUT

      - name: "Build and push container"
        run: |-
          docker build \
            --build-arg API_SERVER=${{ env.API_SERVER }} \
            --build-arg SENTRY_PROJECT="peated-web" \
            --build-arg GOOGLE_CLIENT_ID=${{ env.GOOGLE_CLIENT_ID }} \
            --build-arg SENTRY_DSN=${{ env.SENTRY_DSN }} \
            --target web
            -t "${{ env.GAR_LOCATION }}-docker.pkg.dev/${{ env.PROJECT_ID }}/peated/peated-web:${{ github.sha }}" \
            .
          docker push "${{ env.GAR_LOCATION }}-docker.pkg.dev/${{ env.PROJECT_ID }}/peated/peated-web:${{ github.sha }}"
  deploy:
    name: 🚀 Deploy
    runs-on: ubuntu-latest
    needs: [build]
    steps:
      - name: 🛑 Cancel Previous Runs
        uses: styfle/cancel-workflow-action@0.11.0

      - name: ⬇️ Checkout repo
        uses: actions/checkout@v3

      - name: "Google auth"
        id: "auth"
        uses: "google-github-actions/auth@v1"
        with:
          workload_identity_provider: "${{ secrets.WIF_PROVIDER }}"
          service_account: "${{ secrets.WIF_SERVICE_ACCOUNT }}"

      - name: "Set up Cloud SDK"
        uses: "google-github-actions/setup-gcloud@v1"
        with:
          project_id: "${{ env.PROJECT_ID }}"

      - name: Discord notification (success)
        if: success()
        env:
          DISCORD_WEBHOOK: ${{ secrets.DISCORD_WEBHOOK }}
        uses: Ilshidur/action-discord@0.3.2
        with:
          args: |
            "${{ github.actor }} deployed version [${{ steps.vars.outputs.sha_short }}](https://github.com/{{ EVENT_PAYLOAD.repository.full_name }}/commit/${{ github.sha }})."

      - name: Discord notification (failure)
        if: failure()
        env:
          DISCORD_WEBHOOK: ${{ secrets.DISCORD_WEBHOOK }}
        uses: Ilshidur/action-discord@0.3.2
        with:
          args: |
            "ERROR: Failed to deploy version [${{ steps.vars.outputs.sha_short }}](https://github.com/{{ EVENT_PAYLOAD.repository.full_name }}/commit/${{ github.sha }})."
