name: GCP Deploy
on:
  # TODO: dont ship w/ this!
  pull_request:
  # workflow_run:
  #   branches:
  #     - main
  #   workflows: ["Test"]
  #   types:
  #     - completed
jobs:
  build:
    name: 🚀 Build
    runs-on: ubuntu-latest
    permissions:
      contents: "read"
      id-token: "write"
    env:
      GAR_LOCATION: us-central1
      PROJECT_ID: cask-382601
      GOOGLE_CLIENT_ID: "721909483682-uk3befic1j1krv3drig2puu30v1i4v48.apps.googleusercontent.com"
      SENTRY_DSN: "https://883a3e8bec6a4c4bae25f967d792b492@o172566.ingest.sentry.io/4505138086019073"
      API_SERVER: https://api.peated.app
    steps:
      - name: 🛑 Cancel Previous Runs
        uses: styfle/cancel-workflow-action@0.11.0

      - name: ⬇️ Checkout repo
        uses: actions/checkout@v3

      - name: "Google auth"
        id: "auth"
        uses: "google-github-actions/auth@v1"
        with:
          token_format: access_token
          workload_identity_provider: ${{ secrets.WORKLOAD_IDENTITY_PROVIDER_RESOURCE_NAME }}
          service_account: ${{ secrets.SERVICE_ACCOUNT }}@${{ env.PROJECT_ID }}.iam.gserviceaccount.com
          access_token_lifetime: 300s

      # - name: Login to Artifact Registry
      #   uses: docker/login-action@v1
      #   with:
      #     registry: us-central-docker.pkg.dev
      #     username: oauth2accesstoken
      #     password: ${{ steps.auth.outputs.access_token }}

      - name: "Set up Cloud SDK"
        uses: "google-github-actions/setup-gcloud@v1"
        with:
          project_id: "${{ env.PROJECT_ID }}"

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: "Docker auth"
        run: |-
          gcloud auth configure-docker ${{ env.GAR_LOCATION }}-docker.pkg.dev

      - name: Record Version
        id: vars
        run: echo "sha_short=$(git rev-parse --short HEAD)" >> $GITHUB_OUTPUT

      # - name: "Build Web"
      #   run: |-
      #     docker build \
      #       --cache-from type=gha \
      #       --cache-to type=gha,mode=max \
      #       --build-arg API_SERVER=${{ env.API_SERVER }} \
      #       --build-arg SENTRY_PROJECT="peated-web" \
      #       --build-arg GOOGLE_CLIENT_ID=${{ env.GOOGLE_CLIENT_ID }} \
      #       --build-arg SENTRY_DSN=${{ env.SENTRY_DSN }} \
      #       --target web \
      #       -t "${{ env.GAR_LOCATION }}-docker.pkg.dev/${{ env.PROJECT_ID }}/peated/peated-web:${{ github.sha }}" \
      #       .
      # - name: "Build API"
      #   run: |-
      #     docker build \
      #       --cache-from type=gha \
      #       --cache-to type=gha,mode=max \
      #       --build-arg API_SERVER=${{ env.API_SERVER }} \
      #       --build-arg SENTRY_PROJECT="peated-api" \
      #       --build-arg GOOGLE_CLIENT_ID=${{ env.GOOGLE_CLIENT_ID }} \
      #       --build-arg SENTRY_DSN=${{ env.SENTRY_DSN }} \
      #       --target api \
      #       -t "${{ env.GAR_LOCATION }}-docker.pkg.dev/${{ env.PROJECT_ID }}/peated/peated-api:${{ github.sha }}" \
      #       .
      - name: Build Web
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          target: web
          cache-from: type=gha
          cache-to: type=gha,mode=max
          secrets: |
            "SENTRY_AUTH_TOKEN=${{ secrets.SENTRY_AUTH_TOKEN }}"
          tags: |
            ${{ env.GAR_LOCATION }}-docker.pkg.dev/${{ env.PROJECT_ID }}/peated/peated-web:${{ github.sha }}
            ${{ env.GAR_LOCATION }}-docker.pkg.dev/${{ env.PROJECT_ID }}/peated/peated-web:latest

      - name: Build API
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          target: api
          cache-from: type=gha
          cache-to: type=gha,mode=max
          secrets: |
            "SENTRY_AUTH_TOKEN=${{ secrets.SENTRY_AUTH_TOKEN }}"
          tags: |
            ${{ env.GAR_LOCATION }}-docker.pkg.dev/${{ env.PROJECT_ID }}/peated/peated-api:${{ github.sha }}
            ${{ env.GAR_LOCATION }}-docker.pkg.dev/${{ env.PROJECT_ID }}/peated/peated-api:latest

  deploy:
    name: 🚀 Deploy
    runs-on: ubuntu-latest
    needs: [build]
    permissions:
      contents: "read"
      id-token: "write"
    env:
      GAR_LOCATION: us-central1
      PROJECT_ID: cask-382601
    steps:
      - name: 🛑 Cancel Previous Runs
        uses: styfle/cancel-workflow-action@0.11.0

      - name: ⬇️ Checkout repo
        uses: actions/checkout@v3

      - name: "Google auth"
        id: "auth"
        uses: "google-github-actions/auth@v1"
        with:
          token_format: access_token
          workload_identity_provider: ${{ secrets.WORKLOAD_IDENTITY_PROVIDER_RESOURCE_NAME }}
          service_account: ${{ secrets.SERVICE_ACCOUNT }}@${{ env.PROJECT_ID }}.iam.gserviceaccount.com
          access_token_lifetime: 300s

      - name: "Set up Cloud SDK"
        uses: "google-github-actions/setup-gcloud@v1"
        with:
          project_id: "${{ env.PROJECT_ID }}"

      - name: "Deploy API"
        uses: "google-github-actions/deploy-cloudrun@v1"
        with:
          service: "peated-api"
          image: "${{ env.GAR_LOCATION }}-docker.pkg.dev/${{ env.PROJECT_ID }}/peated/peated-api:${{ github.sha }}"

      - name: "Deploy Web"
        uses: "google-github-actions/deploy-cloudrun@v1"
        with:
          service: "peated-web"
          image: "${{ env.GAR_LOCATION }}-docker.pkg.dev/${{ env.PROJECT_ID }}/peated/peated-web:${{ github.sha }}"

      - name: Discord notification (success)
        if: success()
        env:
          DISCORD_WEBHOOK: ${{ secrets.DISCORD_WEBHOOK }}
        uses: Ilshidur/action-discord@0.3.2
        with:
          args: |
            "${{ github.actor }} deployed version [${{ steps.vars.outputs.sha_short }}](https://github.com/{{ EVENT_PAYLOAD.repository.full_name }}/commit/${{ github.sha }})."

      - name: Discord notification (failure)
        if: failure()
        env:
          DISCORD_WEBHOOK: ${{ secrets.DISCORD_WEBHOOK }}
        uses: Ilshidur/action-discord@0.3.2
        with:
          args: |
            "ERROR: Failed to deploy version [${{ steps.vars.outputs.sha_short }}](https://github.com/{{ EVENT_PAYLOAD.repository.full_name }}/commit/${{ github.sha }})."
